.\llama\llama-server.exe ^
    -m "user_data\models\Qwen3.5-9B-Q3_K_S.gguf" ^
    -c 131072 ^
    --cache-type-k q8_0 ^
    -np 1 ^
    --port 8080 ^
    --host 0.0.0.0 ^
    -ngl 99 ^
    --cache-reuse 256 ^
    --chat-template-kwargs "{\"enable_thinking\": false}" ^
    -fa on ^
    --reasoning off