.\llama\llama-server.exe ^
    -m "user_data\models\Ministral-3-14B-Instruct-2512-UD-IQ2_M.gguf" ^
    -c 131072 ^
    --cache-type-k iq4_nl ^
    --cache-type-v iq4_nl ^
    -np 1 ^
    --port 8080 ^
    --host 0.0.0.0 ^
    -ngl 99 ^
    --cache-reuse 0 ^
    -fa on ^
    --reasoning off