.\llama\llama-server.exe ^
    -m "user_data\models\granite-4.1-8b-Abliterated-AND-Disinhibited.Q4_K_M.gguf" ^
    -c 131072 ^
    --cache-type-k iq4_nl ^
    --cache-type-v iq4_nl ^
    -np 1 ^
    --port 8080 ^
    --host 0.0.0.0 ^
    -ngl 99 ^
    --cache-reuse 1 ^
    -fa on ^
    --reasoning off