/**
 * Base types and interfaces for the LoreReactor application
 * These types represent the fundamental data structures used throughout the system
 */

// ============================================================================
// BASE INTERFACES
// ============================================================================

/**
 * Base interface for all objects with identity and lifecycle tracking
 */
export interface ObjectData {
  id: string;
  name: string;
  description?: string;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;
}

/**
 * Base interface for raw data objects (without ID)
 */
export interface RawData {
  name: string;
  description?: string;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;
}

// ============================================================================
// BACKEND TYPES
// ============================================================================

export type Backend = 
  | 'Llama.cpp' 
  | 'Transformers' 
  | 'ExLlamaV3' 
  | 'ExLlamaV3 HF' 
  | 'TensorRT-LLM' 
  | 'Ollama' 
  | 'DeepSeek' 
  | 'Qwen' 
  | 'Kimi' 
  | 'GLM' 
  | 'MiMo'
  | 'OpenAI' 
  | 'Mistral' 
  | 'Groq'
  | 'YandexGPT' 
  | 'OpenRouter' 
  | 'Inworld' 
  | 'Other';

export type SearchEngine = "Google" | "Bing" | "DuckDuckGo" | "Yandex" | "Baidu";

// ============================================================================
// STOP PATTERN
// ============================================================================

export interface StopPattern extends ObjectData {
  pattern: string;
  regularExpressionActivationTrigger?: string;
  regularExpressionDeactivationTrigger?: string;
  regularExpressionContext?: 'global' | 'local' | 'previous';
  regularExpressionTarget?: 'everyone' | 'listener' | 'self';
}

export interface RawStopPattern extends RawData {
  pattern: string;
  regularExpressionActivationTrigger?: string;
  regularExpressionDeactivationTrigger?: string;
  regularExpressionContext?: 'global' | 'local' | 'previous';
  regularExpressionTarget?: 'everyone' | 'listener' | 'self';
}

// ============================================================================
// SAMPLER
// ============================================================================

export interface Sampler extends ObjectData {
  parameters?: Record<string, unknown>;
  stopPatterns: StopPattern[];
  maximumNumberOfTokens?: number;
}

export interface RawSampler extends RawData {
  parameters?: Record<string, unknown>;
  stopPatternIds: string[];
  maximumNumberOfTokens?: number;
}

// ============================================================================
// CONTEXT
// ============================================================================

export interface Context extends ObjectData {
  text?: string;
  images?: string[];
  searchTerms?: string[];
  searchEngine?: SearchEngine;
  urls?: string[];
  includeLinkImages?: boolean;
  maximumLinkDepth?: number;
  linkFetchMode?: 'full' | 'summary' | 'extract';
  limitLinksToSubdirectory: boolean;
  fetchCacheTimeToLiveMs?: number;
  regularExpressionActivationTrigger?: string;
  regularExpressionDeactivationTrigger?: string;
  regularExpressionContext?: 'global' | 'local' | 'previous';
  regularExpressionTarget?: 'everyone' | 'listener' | 'self';
  tokenBudget?: number;
  maximumRecursionDepth?: number;
  insertionDepth?: number;
  characterBindings?: string[];
  useBase64Encoding: boolean;
  isAutoGenerated?: boolean;
}

export interface RawContext extends RawData {
  text?: string;
  images?: string[];
  searchTerms?: string[];
  searchEngine?: SearchEngine;
  urls?: string[];
  includeLinkImages?: boolean;
  maximumLinkDepth?: number;
  linkFetchMode?: 'full' | 'summary' | 'extract';
  limitLinksToSubdirectory: boolean;
  fetchCacheTimeToLiveMs?: number;
  regularExpressionActivationTrigger?: string;
  regularExpressionDeactivationTrigger?: string;
  regularExpressionContext?: 'global' | 'local' | 'previous';
  regularExpressionTarget?: 'everyone' | 'listener' | 'self';
  tokenBudget?: number;
  maximumRecursionDepth?: number;
  insertionDepth?: number;
  characterBindings?: string[];
  useBase64Encoding: boolean;
  isAutoGenerated?: boolean;
}

// ============================================================================
// LANGUAGE MODEL
// ============================================================================

export interface LanguageModel extends ObjectData {
  backend?: Backend;
  contextLength: number;
  model?: string;
  mmproj?: string;
  lora?: string;
  apiKey?: string;
  parameters?: Record<string, unknown>;
  cacheHitCostPerOneMillionOfTokens?: number;
  cacheMissCostPerOneMillionOfTokens?: number;
  outputGenerationCostPerOneMillionOfTokens?: number;
}

export interface RawLanguageModel extends RawData {
  backend?: Backend;
  contextLength: number;
  model?: string;
  mmproj?: string;
  lora?: string;
  apiKey?: string;
  parameters?: Record<string, unknown>;
  cacheHitCostPerOneMillionOfTokens?: number;
  cacheMissCostPerOneMillionOfTokens?: number;
  outputGenerationCostPerOneMillionOfTokens?: number;
}

// ============================================================================
// MEMORY
// ============================================================================

export interface Memory extends ObjectData {
  content: string;
  chatData: ChatData;
}

export interface RawMemory extends RawData {
  content: string;
  chatDataId: string;
}

// ============================================================================
// CHARACTER
// ============================================================================

export interface Character extends ObjectData {
  image?: string;
  voice?: string;
  systemPrompt?: string;
  thinkPrompt?: string;
  appearancePrompt?: string;
  dialoguePrompt?: string;
  initiativeWeight: number;
  chatProbability: number;
  maximumChatStamina: number;
  nameSensitivity: number;
  responseDelayWeight: number;
  memoryRetentionWeight: number;
  contextSensitivity: number;
  sampler?: Sampler;
  stopPatterns?: StopPattern[];
  doNotInjectCharacterImage?: boolean;
  numberOfMessagesToDisableThinkPrompt: number;
  numberOfMessagesToDisableMetaThinkInstructions: number;
  numberOfMessagesToDisableDialoguePrompt: number;
  enableMemoryWriting: boolean;
  enableMemoryReading: boolean;
  memories: Record<string, Memory[]>;
}

export interface RawCharacter extends RawData {
  image?: string;
  voice?: string;
  systemPrompt?: string;
  thinkPrompt?: string;
  appearancePrompt?: string;
  dialoguePrompt?: string;
  initiativeWeight: number;
  chatProbability: number;
  maximumChatStamina: number;
  nameSensitivity: number;
  responseDelayWeight: number;
  memoryRetentionWeight: number;
  contextSensitivity: number;
  samplerId?: string;
  stopPatternIds?: number[];
  doNotInjectCharacterImage?: boolean;
  numberOfMessagesToDisableThinkPrompt: number;
  numberOfMessagesToDisableMetaThinkInstructions: number;
  numberOfMessagesToDisableDialoguePrompt: number;
  enableMemoryWriting: boolean;
  enableMemoryReading: boolean;
  memories: Record<string, string[]>;
}

// ============================================================================
// CHAT MESSAGE
// ============================================================================

export interface ChatMessage {
  id: string;
  character: Character;
  textContent: string;
  remainingChatStamina: number | undefined;
  isNameRevealed?: boolean;
  isPartial?: boolean;
  textContentSummary?: string;
  kvCachePath?: string;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;
  parentChatMessageId?: string | null;
}

export interface RawChatMessage {
  characterId: string;
  textContent: string;
  remainingChatStamina: number | undefined;
  isNameRevealed?: boolean;
  isPartial?: boolean;
  textContentSummary?: string;
  kvCachePath?: string;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;
  parentChatMessageId?: string | null;
}

// ============================================================================
// CHAT DATA
// ============================================================================

export interface ChatData extends ObjectData {
  protagonist: Character;
  participants: Character[];
  contexts?: Context[];
  chatMessageHistory: ChatMessage[];
  numberOfMessages?: number;
  parentChatDataId?: string | null;
  parentChatMessageId?: string | null;
  Profile?: Profile;
}

export interface RawChatData extends RawData {
  protagonistId: string;
  participantIds: string[];
  contextIds: string[];
  chatMessageIdHistory: string[];
  parentChatDataId?: string | null;
  parentChatMessageId?: string | null;
  ProfileId?: string;
}

// ============================================================================
// EXTENSION
// ============================================================================

export type ExtensionType = 'Image Generation API' | 'Accessibility' | 'Extra';

export interface Extension extends ObjectData {
  extensionType: ExtensionType;
}

// ============================================================================
// BUDGET STRATEGY
// ============================================================================

export interface BudgetStrategy extends ObjectData {
  onlineModel: LanguageModel;
  localModel: LanguageModel;
  switchProbabilty: number;
  switchOnContextSize: number;
  switchOnComplexityScore: number;
  fallbackOnLocalFailure: boolean;
  fallbackOnQualityThreshold: number;
  fallbackOnTimeoutInSeconds: number;
  maximumBudget: number;
}

export interface RawBudgetStrategy extends RawData {
  onlineModelId: string;
  localModelId: string;
  switchProbabilty: number;
  switchOnContextSize: number;
  switchOnComplexityScore: number;
  fallbackOnLocalFailure: boolean;
  fallbackOnQualityThreshold: number;
  fallbackOnTimeoutInSeconds: number;
  maximumBudget: number;
}

// ============================================================================
// SUMMARIZATION
// ============================================================================

export type SummarizationStrategyType = 
  | 'Sliding Window Replace'
  | 'Periodic Compression'
  | 'Recursive Summary'
  | 'Observation Masking';

export interface SummarizationStep extends ObjectData {
  strategyType: SummarizationStrategyType;
  enabled: boolean;
  order: number;
  slidingWindowSize?: number;
  compressionInterval?: number;
  compressionChunkSize?: number;
  recursiveChunkSize?: number;
  recursiveMaxDepth?: number;
  maskingRelevanceThreshold?: number;
  maskingKeywordWeight?: number;
  summaryTokenBudget?: number;
  summaryModelId?: string;
  triggerTokenThreshold?: number;
}

export interface RawSummarizationStep extends RawData {
  strategyType: SummarizationStrategyType;
  enabled: boolean;
  order: number;
  slidingWindowSize?: number;
  compressionInterval?: number;
  compressionChunkSize?: number;
  recursiveChunkSize?: number;
  recursiveMaxDepth?: number;
  maskingRelevanceThreshold?: number;
  maskingKeywordWeight?: number;
  summaryTokenBudget?: number;
  summaryModelId?: string;
  triggerTokenThreshold?: number;
}

// ============================================================================
// PROFILE
// ============================================================================

export type PromptBlockType = 
  | 'System Prompt'
  | 'Think Prompt'
  | 'Meta Think Instruction'
  | 'Appearance Prompt'
  | 'Dialogue Prompt'
  | 'Memory'
  | 'Chat History'
  | 'Context'
  | 'Fatigue Information'
  | 'Date And Time'
  | 'Text Injection';

export interface Profile extends ObjectData {
  forceNameReveal: boolean;
  forceNoCharacterImageInjection: boolean;
  forceNoContextImageInjection: boolean;
  useCurrentDateAndTime: boolean;
  numberOfMessagesToDisableThinkPrompt: number;
  numberOfMessagesToDisableMetaThinkInstructions: number;
  numberOfMessagesToDisableDialoguePrompt: number;
  forceEqualInitiative: boolean;
  chatProbability: number;
  maximumChatStamina: number;
  nameSensitivity: number;
  responseDelayWeight: number;
  memoryRetentionWeight: number;
  contextSensitivity: number;
  cacheInvalidationReductionLevel: number;
  narrateNormalText: boolean;
  narrateQuotedText: boolean;
  narrateBoldedText: boolean;
  narrateItalicizedText: boolean;
  stripThinkTokens: boolean;
  enableMemoryWriting: number;
  enableMemoryReading: number;
  inputStrategy: PromptBlockType[];
  summarizationSteps: SummarizationStep[];
}

export interface RawProfile extends RawData {
  forceNameReveal: boolean;
  forceNoCharacterImageInjection: boolean;
  forceNoContextImageInjection: boolean;
  useCurrentDateAndTime: boolean;
  numberOfMessagesToDisableThinkPrompt: number;
  numberOfMessagesToDisableMetaThinkInstructions: number;
  numberOfMessagesToDisableDialoguePrompt: number;
  forceEqualInitiative: boolean;
  chatProbability: number;
  maximumChatStamina: number;
  nameSensitivity: number;
  responseDelayWeight: number;
  memoryRetentionWeight: number;
  contextSensitivity: number;
  cacheInvalidationReductionLevel: number;
  narrateNormalText: boolean;
  narrateQuotedText: boolean;
  narrateBoldedText: boolean;
  narrateItalicizedText: boolean;
  stripThinkTokens: boolean;
  enableMemoryWriting: number;
  enableMemoryReading: number;
  inputStrategy: PromptBlockType[];
  summarizationSteps: RawSummarizationStep[];
}

// ============================================================================
// WEBPAGE
// ============================================================================

export interface Webpage extends ObjectData {
  url: string;
  content: string;
}

export interface RawWebpage extends RawData {
  url: string;
  content: string;
}

// ============================================================================
// UTILITY INTERFACES
// ============================================================================

export interface InterjectableAction {
  label: string;
  count: number;
}

export interface ParsedCharacterCard {
  name: string;
  description: string;
  firstMes: string;
  personality?: string;
  scenario?: string;
  mesExample?: string;
  creatorNotes?: string;
  systemPrompt?: string;
  postHistoryInstructions?: string;
  alternateGreetings?: string[];
  tags?: string[];
  creator?: string;
  characterVersion?: string;
}
