// frontend_src/components/StandaloneOverlayProfileEditor.tsx
import { useState } from 'react';
import type { Profile, textType, toolUsageDisplayMode } from '../types';
import { SliderInput } from './SliderInput';

interface StandaloneOverlayProfileEditorProps {
    profile: Profile | null;
    onClose: () => void;
    onSave: (profile: Profile) => void;
}

const NARRATE_TEXT_LABELS: Record<textType, string> = {
    normal: 'Normal Text', quoted: 'Quoted Text', bolded: 'Bolded Text',
    italicized: 'Italicized Text', parenthesized: 'Parenthesized Text',
    bracketed: 'Bracketed Text', braced: 'Braced Text',
};

const DEFAULT_NARRATE_TEXTS: Record<textType, boolean> = {
    normal: false, quoted: false, bolded: false, italicized: false,
    parenthesized: false, bracketed: false, braced: false,
};

const TOOL_USAGE_DISPLAY_MODES: { value: toolUsageDisplayMode; label: string; description: string }[] = [
    { value: 'none', label: 'None', description: 'Hide all tool usage from chat output.' },
    { value: 'icon', label: 'Icon', description: 'Show a small icon indicating a tool was used.' },
    { value: 'simple', label: 'Simple', description: 'Show tool name and brief result summary.' },
    { value: 'detailed', label: 'Detailed', description: 'Show tool name, arguments, and formatted results.' },
    { value: 'full', label: 'Full', description: 'Show complete tool invocation including markers and raw output.' },
    { value: 'raw', label: 'Raw', description: 'Show unprocessed tool markers exactly as generated by the model.' },
];

function sliderToDb(sliderValue: number): number {
    const clamped = Math.max(1, Math.min(100, sliderValue));
    return Math.round(-60 + (clamped / 100) * 50);
}

function ProfileCheckbox({ checked, onChange, label, hint, spaced = false }: { checked: boolean; onChange: (checked: boolean) => void; label: string; hint?: string; spaced?: boolean }) {
    return (
        <div className={`pip-profile-checkbox-row ${spaced ? 'spaced' : ''}`}>
            <label className="pip-profile-checkbox-label">
                <input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="editor-checkbox-input" />
                <span className="pip-profile-checkbox-title">{label}</span>
            </label>
            {hint && <div className="pip-profile-checkbox-hint">{hint}</div>}
        </div>
    );
}

export function StandaloneOverlayProfileEditor({ profile, onClose, onSave }: StandaloneOverlayProfileEditorProps) {
    const ep = profile;

    const [name, setName] = useState(ep?.name || '');
    const [description, setDescription] = useState(ep?.description || '');
    const [autonomousMode, setAutonomousMode] = useState(ep?.autonomousMode ?? false);
    const [autonomousInteractionIntervalMs, setAutonomousInteractionIntervalMs] = useState<number>(ep?.autonomousInteractionIntervalMs ?? 10000);

    const [enableAutoSpeechDetection, setEnableAutoSpeechDetection] = useState<boolean>(ep?.enableAutoSpeechDetection ?? false);
    const [speechVolumeActivationThreshold, setSpeechVolumeActivationThreshold] = useState<number>(ep?.speechVolumeActivationThreshold ?? 18);
    const [speechSilenceVolumeActivationThreshold, setSpeechSilenceVolumeActivationThreshold] = useState<number>(ep?.speechSilenceVolumeActivationThreshold ?? 8);
    const [speechSilenceThresholdMs, setSpeechSilenceThresholdMs] = useState<number>(ep?.speechSilenceThresholdMs ?? 1400);

    const [forceNameReveal, setForceNameReveal] = useState(ep?.forceNameReveal ?? false);
    const [enableAmbientNarration, setEnableAmbientNarration] = useState(ep?.enableAmbientNarration ?? false);
    const [toolUsageDisplayMode, setToolUsageDisplayMode] = useState<toolUsageDisplayMode>(ep?.toolUsageDisplayMode ?? 'none');
    const [enableCharacterExpression, setEnableCharacterExpression] = useState(ep?.enableCharacterExpression ?? false);
    
    const [volume, setVolume] = useState<number>(ep?.volume ?? -1);
    const [stripThinkTokens, setStripThinkTokens] = useState(ep?.stripThinkTokens ?? false);
    const [narrateTexts, setNarrateTexts] = useState<Record<textType, boolean>>(ep?.narrateTexts ?? { ...DEFAULT_NARRATE_TEXTS });

    const handleNarrateToggle = (type: textType, checked: boolean) => setNarrateTexts(prev => ({ ...prev, [type]: checked }));
    const selectedToolUsageDisplayMode = TOOL_USAGE_DISPLAY_MODES.find(m => m.value === toolUsageDisplayMode) ?? TOOL_USAGE_DISPLAY_MODES[0];

    const handleSubmit = () => {
        if (!ep) return;
        onSave({
            ...ep,
            name, description: description.trim() || undefined,
            autonomousMode, autonomousInteractionIntervalMs,
            enableAutoSpeechDetection, speechVolumeActivationThreshold, speechSilenceVolumeActivationThreshold, speechSilenceThresholdMs,
            forceNameReveal, enableAmbientNarration, toolUsageDisplayMode, enableCharacterExpression,
            volume, stripThinkTokens, narrateTexts: { ...narrateTexts },
            lastUpdatedTimestamp: Date.now(),
        });
        onClose();
    };

    return (
        <div className="pip-modal-overlay" onClick={onClose}>
            <div className="pip-modal-content" onClick={e => e.stopPropagation()}>
                <div className="pip-modal-header">
                    <h2 className="pip-modal-title">Edit Profile</h2>
                    <div className="pip-editor-actions">
                        <button type="button" className="pip-editor-btn-cancel" onClick={onClose}>Cancel</button>
                        <button type="button" className="pip-editor-btn-save" onClick={handleSubmit}>Save</button>
                    </div>
                </div>

                <div className="pip-editor-modal-body">
                    <div className="pip-editor-field-group">
                        <label className="editor-label">Name <span className="pip-required-asterisk">*</span></label>
                        <input type="text" value={name} onChange={(e) => setName(e.target.value)} className="editor-input" />
                    </div>

                    <div className="pip-editor-field-group">
                        <label className="editor-label">Description</label>
                        <textarea value={description} onChange={(e) => setDescription(e.target.value)} className="editor-textarea" rows={2} />
                    </div>

                    <div className="pip-editor-section">
                        <span className="pip-editor-section-title">Agentic Roleplay</span>
                        <ProfileCheckbox checked={autonomousMode} onChange={setAutonomousMode} label="Autonomous Mode" hint="Characters act independently in the background." />
                        {autonomousMode && (
                            <div className="pip-slider-container">
                                <div className="pip-slider-header">
                                    <label className="pip-slider-label">Interaction Interval</label>
                                    <span className="pip-slider-value">{(autonomousInteractionIntervalMs / 1000).toFixed(1)}s</span>
                                </div>
                                <SliderInput label="" value={autonomousInteractionIntervalMs} minimumValue={1000} maximumValue={60000} stepValue={1000} decimals={0} onChange={(val) => setAutonomousInteractionIntervalMs(Math.round(val))} description="How often the engine evaluates characters for autonomous actions." />
                            </div>
                        )}
                    </div>

                    <div className="pip-editor-section">
                        <span className="pip-editor-section-title">Voice Activity Detection & Auto-Send</span>
                        <ProfileCheckbox checked={enableAutoSpeechDetection} onChange={setEnableAutoSpeechDetection} label="Auto-Send Voice Input (Hands-Free VAD)" hint="Automatically detect when you start and stop speaking." />
                        {enableAutoSpeechDetection && (
                            <>
                                <div className="pip-slider-container">
                                    <div className="pip-slider-header">
                                        <label className="pip-slider-label">Speech Activation Threshold</label>
                                        <span className="pip-slider-value">{speechVolumeActivationThreshold}% ({sliderToDb(speechVolumeActivationThreshold)} dBFS)</span>
                                    </div>
                                    <SliderInput label="" value={speechVolumeActivationThreshold} minimumValue={1} maximumValue={100} stepValue={1} decimals={0} onChange={(val) => setSpeechVolumeActivationThreshold(Math.round(val))} description="How loud you must speak to wake up the engine." />
                                </div>
                                <div className="pip-slider-container">
                                    <div className="pip-slider-header">
                                        <label className="pip-slider-label">Silence Deactivation Threshold</label>
                                        <span className="pip-slider-value">{speechSilenceVolumeActivationThreshold}% ({sliderToDb(speechSilenceVolumeActivationThreshold)} dBFS)</span>
                                    </div>
                                    <SliderInput label="" value={speechSilenceVolumeActivationThreshold} minimumValue={1} maximumValue={100} stepValue={1} decimals={0} onChange={(val) => setSpeechSilenceVolumeActivationThreshold(Math.round(val))} description="The lower volume cutoff that triggers the silence countdown." />
                                </div>
                                <div className="pip-slider-container">
                                    <div className="pip-slider-header">
                                        <label className="pip-slider-label">Silence Pause Duration</label>
                                        <span className="pip-slider-value">{(speechSilenceThresholdMs / 1000).toFixed(1)}s</span>
                                    </div>
                                    <SliderInput label="" value={speechSilenceThresholdMs} minimumValue={500} maximumValue={5000} stepValue={100} decimals={0} onChange={(val) => setSpeechSilenceThresholdMs(Math.round(val))} description="Duration of silence below the cutoff before final transcription is fired." />
                                </div>
                            </>
                        )}
                    </div>

                    <div className="pip-editor-section">
                        <span className="pip-editor-section-title">Volume</span>
                        <div className="pip-slider-container">
                            <div className="pip-slider-header">
                                <label className="pip-slider-label">Global Volume Override</label>
                                <span className="pip-slider-value">{volume === -1 ? '(Per-track default)' : `${Math.round(volume * 100)}%`}</span>
                            </div>
                            <div className="pip-volume-slider-wrapper">
                                <input type="range" min="-1" max="1" step="0.01" value={volume} onChange={(e) => setVolume(Number(e.target.value))} className="pip-volume-range-input" />
                            </div>
                            <div className="pip-field-hint">-1 = use each track's own volume. ≥0 = override all tracks uniformly.</div>
                        </div>
                    </div>

                    <div className="pip-editor-section">
                        <span className="pip-editor-section-title">Display</span>
                        <ProfileCheckbox checked={forceNameReveal} onChange={setForceNameReveal} label="Force Name Reveal" hint='Always show character names instead of "Character X".' />
                        <ProfileCheckbox checked={enableAmbientNarration} onChange={setEnableAmbientNarration} label="Enable Ambient Narration" hint="Generate environmental narration to fill silence." spaced />
                        <div className="pip-editor-field-group">
                            <label className="editor-label">Tool Usage Display Mode</label>
                            <select value={toolUsageDisplayMode} onChange={(e) => setToolUsageDisplayMode(e.target.value as toolUsageDisplayMode)} className="pip-editor-select">
                                {TOOL_USAGE_DISPLAY_MODES.map(mode => (<option key={mode.value} value={mode.value}>{mode.label}</option>))}
                            </select>
                            <div className="pip-field-hint">{selectedToolUsageDisplayMode.description}</div>
                        </div>
                        <ProfileCheckbox checked={enableCharacterExpression} onChange={setEnableCharacterExpression} label="Enable Character Expression" hint="Use sentiment analysis to swap character images based on emotional tone." />
                    </div>

                    <div className="pip-editor-section">
                        <span className="pip-editor-section-title">Voice Narration</span>
                        <div className="pip-voice-narration-grid">
                            {(Object.keys(NARRATE_TEXT_LABELS) as textType[]).map(type => (
                                <label key={type} className="pip-voice-narration-toggle">
                                    <input type="checkbox" checked={narrateTexts[type]} onChange={(e) => handleNarrateToggle(type, e.target.checked)} className="editor-checkbox-input" />
                                    <span className="pip-voice-narration-text">{NARRATE_TEXT_LABELS[type]}</span>
                                </label>
                            ))}
                        </div>
                    </div>

                    <div className="pip-editor-section">
                        <span className="pip-editor-section-title">Output Processing</span>
                        <ProfileCheckbox checked={stripThinkTokens} onChange={setStripThinkTokens} label="Strip Think Tokens" hint="Remove thinking tokens from displayed output." />
                    </div>
                </div>
            </div>
        </div>
    );
}