// src/components/ProfileEditorModal.tsx
import { useState, useMemo, useCallback, type CSSProperties } from 'react';
import type { Profile, PromptBlock, promptBlockType, SummarizationStep, SummarizationStrategyType, tool, textType, toolUsageDisplayMode, Sampler, StopPattern, tristateInteger, cacheEfficiencyConfigurationType, AutoResumeSignal } from '../types';
import { SliderInput } from './SliderInput';
import '../main.css';
import { defaultInputStrategy, defaultProfileTools } from '../dictionaries/defaults';
import { toolLabels } from '../dictionaries/texts';
import { v4 as uuidv4 } from 'uuid';

interface ProfileEditorModalProps {
    onClose: () => void;
    onSave: (profile: Profile) => void;
    existingProfile?: Profile | null;
    allPromptBlocks?: PromptBlock[];
    allSamplers?: Sampler[];
    allStopPatterns?: StopPattern[];
}

const CACHE_EFFICIENCY_DESCRIPTIONS: Record<cacheEfficiencyConfigurationType, string[]> = {
    'Character Name': [
        'No optimization. Names resolved dynamically per turn.',
        'Freeze names for co-located participants only.',
        'Freeze names for all participants regardless of location.',
    ],
    'System Prompt': [
        'Only current character\'s system prompt injected.',
        'Inject co-located participants\' system prompts upfront.',
        'Inject ALL participants\' system prompts upfront.',
    ],
    'Think Prompt': [
        'Only current character\'s think prompt injected.',
        'Inject co-located participants\' think prompts upfront.',
        'Inject ALL participants\' think prompts upfront.',
    ],
};

const STRATEGY_DESCRIPTIONS: Record<SummarizationStrategyType, string> = {
    'Sliding Window Replace': 'Replace old messages with per-message summaries beyond the window size.',
    'Periodic Compression': 'Compress every M messages into a summary paragraph at regular intervals.',
    'Recursive Summary': 'Build hierarchical summaries: chunks → meta-summaries → global summary.',
    'Observation Masking': 'Hide older messages by relevance score. Keep only what matters to the current context.',
    'Entropy Pruning': 'Compress redundant, low-information scenes while preserving sharp, information-dense moments in raw context.',
};

const ALL_STRATEGY_TYPES: SummarizationStrategyType[] = [
    'Sliding Window Replace', 'Periodic Compression', 'Recursive Summary', 'Observation Masking', 'Entropy Pruning',
];

const NARRATE_TEXT_LABELS: Record<textType, string> = {
    normal: 'Normal Text', quoted: 'Quoted Text', bolded: 'Bolded Text',
    italicized: 'Italicized Text', parenthesized: 'Parenthesized Text',
    bracketed: 'Bracketed Text', braced: 'Braced Text',
};

const DEFAULT_NARRATE_TEXTS: Record<textType, boolean> = {
    normal: false, quoted: false, bolded: false, italicized: false,
    parenthesized: false, bracketed: false, braced: false,
};

const TOOL_USAGE_DISPLAY_MODES: { value: toolUsageDisplayMode; label: string; description: string }[] = [
    { value: 'none', label: 'None', description: 'Hide all tool usage from chat output.' },
    { value: 'icon', label: 'Icon', description: 'Show a small icon indicating a tool was used.' },
    { value: 'simple', label: 'Simple', description: 'Show tool name and brief result summary.' },
    { value: 'detailed', label: 'Detailed', description: 'Show tool name, arguments, and formatted results.' },
    { value: 'full', label: 'Full', description: 'Show complete tool invocation including markers and raw output.' },
    { value: 'raw', label: 'Raw', description: 'Show unprocessed tool markers exactly as generated by the model.' },
];

function mergeToolsWithDefaults(saved: Partial<Record<tool, tristateInteger>> | undefined): Record<tool, tristateInteger> {
    const merged: Record<tool, tristateInteger> = {} as Record<tool, tristateInteger>;
    for (const key of Object.keys(defaultProfileTools) as tool[]) {
        merged[key] = saved?.[key] !== undefined && typeof saved[key] === 'number' 
            ? (saved[key] as tristateInteger) 
            : defaultProfileTools[key];
    }
    return merged;
}

function getDefaultSummarizationSteps(): SummarizationStep[] {
    const now = Date.now();
    return [
        { id: `step-${uuidv4()}`, name: 'Sliding Window Replace', strategyType: 'Sliding Window Replace', enabled: true, order: 0, slidingWindowSize: 10, summaryTokenBudget: 256, triggerTokenThreshold: 0, firstCreatedTimestamp: now, lastUpdatedTimestamp: now },
        { id: `step-${uuidv4()}`, name: 'Periodic Compression', strategyType: 'Periodic Compression', enabled: false, order: 1, periodicCompressionInterval: 20, periodicCompressionChunkSize: 10, summaryTokenBudget: 512, triggerTokenThreshold: 0, firstCreatedTimestamp: now, lastUpdatedTimestamp: now },
        { id: `step-${uuidv4()}`, name: 'Recursive Summary', strategyType: 'Recursive Summary', enabled: false, order: 2, recursiveSummaryChunkSize: 10, recursiveSummaryMaximumDepth: 3, summaryTokenBudget: 1024, triggerTokenThreshold: 0, firstCreatedTimestamp: now, lastUpdatedTimestamp: now },
        { id: `step-${uuidv4()}`, name: 'Observation Masking', strategyType: 'Observation Masking', enabled: false, order: 3, maskingRelevanceThreshold: 0.3, maskingKeywordWeight: 0.7, triggerTokenThreshold: 0, firstCreatedTimestamp: now, lastUpdatedTimestamp: now },
        { id: `step-${uuidv4()}`, name: 'Entropy Pruning', strategyType: 'Entropy Pruning', enabled: false, order: 4, entropyPruningChunkSize: 3, entropyPruningThreshold: 0.35, entropyPruningTokenBudget: 2000, summaryTokenBudget: 256, triggerTokenThreshold: 0, firstCreatedTimestamp: now, lastUpdatedTimestamp: now },
    ];
}

const ALL_BUILT_IN_BLOCK_TYPES = [...defaultInputStrategy, 'Model Instruction Template', 'Model Chat Template', 'Model Chat-Instruction Template']

function isBuiltInBlockType(value: string): value is promptBlockType {
    return (ALL_BUILT_IN_BLOCK_TYPES as string[]).includes(value);
}

function migrateNarrateTexts(profile: Profile): Record<textType, boolean> {
    if (profile.narrateTexts) return { ...DEFAULT_NARRATE_TEXTS, ...profile.narrateTexts };
    const p = profile as unknown as Record<string, unknown>;
    return {
        normal: (p.narrateNormalText as boolean) ?? DEFAULT_NARRATE_TEXTS.normal,
        quoted: (p.narrateQuotedText as boolean) ?? DEFAULT_NARRATE_TEXTS.quoted,
        bolded: (p.narrateBoldedText as boolean) ?? DEFAULT_NARRATE_TEXTS.bolded,
        italicized: (p.narrateItalicizedText as boolean) ?? DEFAULT_NARRATE_TEXTS.italicized,
        parenthesized: DEFAULT_NARRATE_TEXTS.parenthesized,
        bracketed: DEFAULT_NARRATE_TEXTS.bracketed,
        braced: DEFAULT_NARRATE_TEXTS.braced,
    };
}

const CHECKBOX_HINT_STYLE: CSSProperties = { fontSize: '0.65rem', opacity: 0.6, marginTop: '4px', marginLeft: '26px' };
const SLIDER_HEADER_STYLE: CSSProperties = { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '4px' };
const SLIDER_LABEL_STYLE: CSSProperties = { margin: 0 };
const SLIDER_VALUE_STYLE: CSSProperties = { fontSize: '0.65rem', opacity: 0.6 };
const TOOLBAR_BTN_SMALL_STYLE: CSSProperties = { width: '24px', height: '24px', fontSize: '0.7rem' };
const TOOLBAR_BTN_DELETE_STYLE: CSSProperties = { ...TOOLBAR_BTN_SMALL_STYLE, fontSize: '0.8rem', color: '#ff4444' };
const STEP_EXPANDED_STYLE: CSSProperties = {
    padding: '10px 12px', margin: '0 0 4px 0', background: 'var(--social-bg)',
    border: '1px solid var(--border)', borderTop: 'none', borderRadius: '0 0 6px 6px',
    display: 'flex', flexDirection: 'column', gap: '8px',
};
const STEP_NAME_STYLE: CSSProperties = { fontSize: '0.75rem', fontWeight: 'bold', color: 'var(--text-h)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' };
const STEP_DESC_STYLE: CSSProperties = { fontSize: '0.65rem', opacity: 0.6, fontStyle: 'italic' };
const INPUT_RIGHT_STYLE: CSSProperties = { textAlign: 'right' as const };
const FIELD_HINT_STYLE: CSSProperties = { fontSize: '0.55rem', opacity: 0.5, marginTop: '2px' };

type ProfileTabId = 'general' | 'injection' | 'behaviour' | 'tools' | 'pipeline' | 'cache' | 'model';

function ProfileCheckbox({ checked, onChange, label, hint, spaced = false }: { checked: boolean; onChange: (checked: boolean) => void; label: string; hint?: string; spaced?: boolean }) {
    return (
        <div className={`profile-checkbox-row ${spaced ? 'profile-checkbox-spaced' : ''}`}>
            <label className="editor-checkbox-label profile-checkbox-left">
                <input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="editor-checkbox-input" />
                <span>{label}</span>
            </label>
            {hint && <div className="profile-checkbox-hint">{hint}</div>}
        </div>
    );
}

function StopPatternSelect({
    label,
    value,
    onChange,
    allStopPatterns,
}: {
    label: string;
    value: string;
    onChange: (id: string) => void;
    allStopPatterns: StopPattern[];
}) {
    return (
        <div>
            <label className="editor-label editor-label-small">{label}</label>
            <select value={value} onChange={(e) => onChange(e.target.value)} className="editor-select">
                <option value="">(None)</option>
                {allStopPatterns.map(sp => <option key={sp.id} value={sp.id}>{sp.name}</option>)}
            </select>
        </div>
    );
}

export function ProfileEditorModal({
    existingProfile, onClose, onSave, allPromptBlocks = [], allSamplers = [], allStopPatterns = [],
}: ProfileEditorModalProps) {
    const [activeTab, setActiveTab] = useState<ProfileTabId>('general');
    const ep = existingProfile ?? null;

    const [name, setName] = useState(ep?.name || '');
    const [description, setDescription] = useState(ep?.description || '');
    const [autonomousMode, setAutonomousMode] = useState(ep?.autonomousMode ?? false);
    const [autonomousInteractionIntervalMs, setAutonomousInteractionIntervalMs] = useState<number>(ep?.autonomousInteractionIntervalMs ?? 10000);
    const [forceNameReveal, setForceNameReveal] = useState(ep?.forceNameReveal ?? false);
    const [enableAmbientNarration, setEnableAmbientNarration] = useState(ep?.enableAmbientNarration ?? false);
    const [toolUsageDisplayMode, setToolUsageDisplayMode] = useState<toolUsageDisplayMode>(ep?.toolUsageDisplayMode ?? 'none');
    const [enableCharacterExpression, setEnableCharacterExpression] = useState(ep?.enableCharacterExpression ?? false);
    const [randomizeTextCharacterInjection, setRandomizeTextCharacterInjection] = useState<boolean>(ep?.randomizeTextCharacterInjection ?? false);
    const [randomizeTextCharacterInjectionOnRetry, setRandomizeTextCharacterInjectionOnRetry] = useState<boolean>(ep?.randomizeTextCharacterInjectionOnRetry ?? true);
    const [maximumNumberOfTextCharacterRandomizationPerModel, setMaximumNumberOfTextCharacterRandomizationPerModel] = useState<number>(ep?.maximumNumberOfTextCharacterRandomizationPerModel ?? 1);
    const [forceNoCharacterImageInjection, setForceNoCharacterImageInjection] = useState(ep?.forceNoCharacterImageInjection ?? false);
    const [numberOfMessagesToDisableThinkPrompt, setNumberOfMessagesToDisableThinkPrompt] = useState<number>(ep?.numberOfMessagesToDisableThinkPrompt ?? -1);
    const [numberOfMessagesToDisableMetaThinkInstructions, setNumberOfMessagesToDisableMetaThinkInstructions] = useState<number>(ep?.numberOfMessagesToDisableMetaThinkInstructions ?? -1);
    const [numberOfMessagesToDisableDialoguePrompt, setNumberOfMessagesToDisableDialoguePrompt] = useState<number>(ep?.numberOfMessagesToDisableDialoguePrompt ?? -1);
    const [numberOfMessagesToDisableStarterPrompt, setNumberOfMessagesToDisableStarterPrompt] = useState<number>(ep?.numberOfMessagesToDisableStarterPrompt ?? -1);
    const [forceNoContextImageInjection, setForceNoContextImageInjection] = useState(ep?.forceNoContextImageInjection ?? false);
    const [forceNoLocationImageInjection, setForceNoLocationImageInjection] = useState(ep?.forceNoLocationImageInjection ?? false);
    const [weatherApiKey, setWeatherApiKey] = useState(ep?.weatherApiKey ?? '');
    const [useFrontCameraImage, setUseFrontCameraImage] = useState<tristateInteger>((ep?.useFrontCameraImage ?? 0) as tristateInteger);
    const [forceEqualInitiative, setForceEqualInitiative] = useState(ep?.forceEqualInitiative ?? false);
    const [chatProbability, setChatProbability] = useState<number>(ep?.chatProbability ?? -1);
    const [maximumChatStamina, setMaximumChatStamina] = useState<number>(ep?.maximumChatStamina ?? -1);
    const [nameSensitivity, setNameSensitivity] = useState<number>(ep?.nameSensitivity ?? -1);
    const [skipProbability, setSkipProbability] = useState<number>(ep?.skipProbability ?? -1);
    const [chatImpatienceSensitivity, setChatImpatienceSensitivity] = useState<number>(ep?.chatImpatienceSensitivity ?? -1);
    const [memoryRetentionWeight, setMemoryRetentionWeight] = useState<number>(ep?.memoryRetentionWeight ?? -1);
    const [contextSensitivity, setContextSensitivity] = useState<number>(ep?.contextSensitivity ?? -1);
    const [maximumActionStamina, setMaximumActionStamina] = useState<number>(ep?.maximumActionStamina ?? -1);
    const [doNotInjectDefaultStopTokens, setDoNotInjectDefaultStopTokens] = useState(ep?.doNotInjectDefaultStopTokens ?? false);
    const [enableSpeculativeMarkov, setEnableSpeculativeMarkov] = useState(ep?.enableSpeculativeMarkov ?? false);
    const [volume, setVolume] = useState<number>(ep?.volume ?? -1);
    const [stripThinkTokens, setStripThinkTokens] = useState(ep?.stripThinkTokens ?? false);
    
    const [tools, setTools] = useState<Record<tool, tristateInteger>>(mergeToolsWithDefaults(ep?.tools));
    const [toolSearchQuery, setToolSearchQuery] = useState('');
    const [narrateTexts, setNarrateTexts] = useState<Record<textType, boolean>>(ep ? migrateNarrateTexts(ep) : { ...DEFAULT_NARRATE_TEXTS });
    const [inputStrategy, setInputStrategy] = useState<(promptBlockType | string)[]>(ep?.inputStrategy?.length ? ep.inputStrategy : [...defaultInputStrategy]);
    const [summarizationSteps, setSummarizationSteps] = useState<SummarizationStep[]>(
        ep?.summarizationSteps != null ? [...ep.summarizationSteps].sort((a, b) => a.order - b.order) : getDefaultSummarizationSteps()
    );
    const [summarizationInstruction, setSummarizationInstruction] = useState<string>(ep?.summarizationInstruction || '');
    
    // ─── Auto-Resume Signals State ─────────────────────────────────────
    const [autoResumeSignals, setAutoResumeSignals] = useState<AutoResumeSignal[]>(ep?.autoResumeSignals ?? []);
    const [expandedSignalIndex, setExpandedSignalIndex] = useState<number | null>(null);

    const handleAddAutoResumeSignal = useCallback(() => {
        setAutoResumeSignals(prev => [...prev, { stopPattern: '', minimumLength: '0', maximumNumberOfAutoResumes: 10 }]);
    }, []);

    const handleUpdateAutoResumeSignal = useCallback((index: number, field: keyof AutoResumeSignal, value: string) => {
        setAutoResumeSignals(prev => {
            const next = [...prev];
            if (field === 'maximumNumberOfAutoResumes') {
                const numVal = Number(value);
                next[index] = { ...next[index], [field]: isNaN(numVal) ? 0 : numVal };
            } else {
                next[index] = { ...next[index], [field]: value as any };
            }
            return next;
        });
    }, []);

    const handleRemoveAutoResumeSignal = useCallback((index: number) => {
        setAutoResumeSignals(prev => prev.filter((_, i) => i !== index));
        if (expandedSignalIndex === index) setExpandedSignalIndex(null);
    }, [expandedSignalIndex]);
    // ───────────────────────────────────────────────────────────────────

    const [characterSamplerId, setCharacterSamplerId] = useState<string>(ep?.characterSampler?.id ?? '');
    const [webSummarizationSamplerId, setWebSummarizationSamplerId] = useState<string>(ep?.webSummarizationSampler?.id ?? '');
    const [interactionDataSummarizationSamplerId, setInteractionDataSummarizationSamplerId] = useState<string>(ep?.interactionDataSummarizationSampler?.id ?? '');
    const [aiRecommendationSamplerId, setAiRecommendationSamplerId] = useState<string>(ep?.aiRecommendationSampler?.id ?? '');
    const [characterStopPatternId, setCharacterStopPatternId] = useState<string>(ep?.characterStopPattern?.id ?? '');
    const [webSummarizationStopPatternId, setWebSummarizationStopPatternId] = useState<string>(ep?.webSummarizationStopPattern?.id ?? '');
    const [interactionDataSummarizationStopPatternId, setInteractionDataSummarizationStopPatternId] = useState<string>(ep?.interactionDataSummarizationStopPattern?.id ?? '');
    const [aiRecommendationStopPatternId, setAiRecommendationStopPatternId] = useState<string>(ep?.aiRecommendationStopPattern?.id ?? '');
    const [errors, setErrors] = useState<{ name?: string }>({});
    const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
    const [draggedStepIndex, setDraggedStepIndex] = useState<number | null>(null);
    const [expandedStepId, setExpandedStepId] = useState<string | null>(null);

    // ─── Cache Efficiency State ─────────────────────────────────────
    const defaultCacheLevels: Record<cacheEfficiencyConfigurationType, number> = { 'Character Name': 0, 'System Prompt': 0, 'Think Prompt': 0 };
    const [cacheEfficiencyLevels, setCacheEfficiencyLevels] = useState<Record<cacheEfficiencyConfigurationType, number>>(
        ep?.cacheEfficiencyLevels ?? { ...defaultCacheLevels }
    );
    const [minimalVolatileCacheMode, setMinimalVolatileCacheMode] = useState<boolean>(ep?.minimalVolatileCacheMode ?? false);

    const promptBlockById = useMemo(() => {
        const map = new Map<string, PromptBlock>();
        for (const pb of allPromptBlocks) map.set(pb.id, pb);
        return map;
    }, [allPromptBlocks]);

    const getBlockLabel = (entry: promptBlockType | string): string => {
        if (isBuiltInBlockType(entry)) return entry;
        const pb = promptBlockById.get(entry);
        return pb ? `🧱 ${pb.name}` : "🧱 (Unknown Block)";
    };

    const handleToolChange = (toolName: tool, value: tristateInteger) => setTools(prev => ({ ...prev, [toolName]: value }));
    const handleNarrateToggle = (type: textType, checked: boolean) => setNarrateTexts(prev => ({ ...prev, [type]: checked }));
    const handleCacheLevelChange = (category: cacheEfficiencyConfigurationType, value: number) => {
        setCacheEfficiencyLevels(prev => ({ ...prev, [category]: Math.round(value) }));
    };

    // ─── Tool Bulk Actions ──────────────────────────────────────────
    const handleSelectAllTools = useCallback(() => {
        setTools(prev => {
            const next = { ...prev };
            for (const key of Object.keys(next) as tool[]) next[key] = 1;
            return next;
        });
    }, []);

    const handleDeselectAllTools = useCallback(() => {
        setTools(prev => {
            const next = { ...prev };
            for (const key of Object.keys(next) as tool[]) next[key] = -1;
            return next;
        });
    }, []);

    const handleResetToolsToDefaults = useCallback(() => {
        setTools({ ...defaultProfileTools });
    }, []);

    const validate = (): boolean => {
        const newErrors: { name?: string } = {};
        if (!name.trim()) newErrors.name = 'Name is required.';
        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const buildProfile = (id: string, profileName: string): Profile => {
        const now = Date.now();
        const getSampler = (sId: string) => allSamplers.find(s => s.id === sId);
        const getStopPattern = (spId: string) => allStopPatterns.find(sp => sp.id === spId);
        return {
            id, name: profileName, description: description.trim() || undefined,
            autonomousMode, autonomousInteractionIntervalMs,
            forceNameReveal, enableAmbientNarration, toolUsageDisplayMode, enableCharacterExpression,
            randomizeTextCharacterInjection,
            randomizeTextCharacterInjectionOnRetry,
            maximumNumberOfTextCharacterRandomizationPerModel,
            forceNoCharacterImageInjection, forceNoContextImageInjection, forceNoLocationImageInjection,
            numberOfMessagesToDisableThinkPrompt, numberOfMessagesToDisableMetaThinkInstructions, numberOfMessagesToDisableDialoguePrompt, numberOfMessagesToDisableStarterPrompt,
            weatherApiKey,
            useFrontCameraImage,
            forceEqualInitiative, chatProbability, maximumChatStamina,
            nameSensitivity, skipProbability, chatImpatienceSensitivity,
            memoryRetentionWeight, contextSensitivity, maximumActionStamina,
            cacheEfficiencyLevels: { ...cacheEfficiencyLevels },
            minimalVolatileCacheMode,
            doNotInjectDefaultStopTokens,
            enableSpeculativeMarkov,
            volume, stripThinkTokens, tools: { ...tools },
            narrateTexts: { ...narrateTexts },
            inputStrategy: [...inputStrategy],
            summarizationSteps: summarizationSteps.map((s, i) => ({
                ...s, id: s.id || `step-${uuidv4()}`, order: i,
                firstCreatedTimestamp: s.firstCreatedTimestamp || now, lastUpdatedTimestamp: now,
            })),
            summarizationInstruction: summarizationInstruction.trim() || undefined,
            autoResumeSignals: [...autoResumeSignals],
            characterSampler: getSampler(characterSamplerId),
            webSummarizationSampler: getSampler(webSummarizationSamplerId),
            interactionDataSummarizationSampler: getSampler(interactionDataSummarizationSamplerId),
            aiRecommendationSampler: getSampler(aiRecommendationSamplerId),
            characterStopPattern: getStopPattern(characterStopPatternId),
            webSummarizationStopPattern: getStopPattern(webSummarizationStopPatternId),
            interactionDataSummarizationStopPattern: getStopPattern(interactionDataSummarizationStopPatternId),
            aiRecommendationStopPattern: getStopPattern(aiRecommendationStopPatternId),
            firstCreatedTimestamp: ep?.firstCreatedTimestamp || now,
            lastUpdatedTimestamp: now,
        };
    };

    const handleSubmit = () => { if (!validate()) return; onSave(buildProfile(ep?.id || uuidv4(), name.trim())); onClose(); };
    const handleClone = () => { if (!validate()) return; onSave(buildProfile(uuidv4(), `${name.trim()} (Clone)`)); onClose(); };

    const handleDragStart = (e: React.DragEvent, index: number) => { setDraggedIndex(index); e.dataTransfer.effectAllowed = 'move'; e.dataTransfer.setData('text/plain', String(index)); setTimeout(() => { (e.target as HTMLElement).style.opacity = '0.5'; }, 0); };
    const handleDragEnd = (e: React.DragEvent) => { (e.target as HTMLElement).style.opacity = '1'; setDraggedIndex(null); };
    const handleDragOver = (e: React.DragEvent) => { e.preventDefault(); e.dataTransfer.dropEffect = 'move'; };
    const handleDrop = (e: React.DragEvent, dropIndex: number) => { e.preventDefault(); const dragIndex = Number.parseInt(e.dataTransfer.getData('text/plain')); if (dragIndex === dropIndex) return; const newOrder = [...inputStrategy]; const [removed] = newOrder.splice(dragIndex, 1); newOrder.splice(dropIndex, 0, removed); setInputStrategy(newOrder); setDraggedIndex(null); };
    const moveBlock = (index: number, direction: -1 | 1) => { const newIndex = index + direction; if (newIndex < 0 || newIndex >= inputStrategy.length) return; const newOrder = [...inputStrategy]; [newOrder[index], newOrder[newIndex]] = [newOrder[newIndex], newOrder[index]]; setInputStrategy(newOrder); };
    const addBlock = (blockEntry: promptBlockType | string) => { if (!inputStrategy.includes(blockEntry)) setInputStrategy(prev => [...prev, blockEntry]); };
    const removeBlock = (index: number) => { setInputStrategy(prev => prev.filter((_, i) => i !== index)); };

    const missingBuiltInBlocks = ALL_BUILT_IN_BLOCK_TYPES.filter(b => !inputStrategy.includes(b) && b !== 'Memory');
    const availablePromptBlocks = allPromptBlocks.filter((pb: PromptBlock) => !inputStrategy.includes(pb.id));

    const handleStepDragStart = (e: React.DragEvent, index: number) => { setDraggedStepIndex(index); e.dataTransfer.effectAllowed = 'move'; e.dataTransfer.setData('text/plain', String(index)); setTimeout(() => { (e.target as HTMLElement).style.opacity = '0.5'; }, 0); };
    const handleStepDragEnd = (e: React.DragEvent) => { (e.target as HTMLElement).style.opacity = '1'; setDraggedStepIndex(null); };
    const handleStepDrop = (e: React.DragEvent, dropIndex: number) => { e.preventDefault(); const dragIndex = Number.parseInt(e.dataTransfer.getData('text/plain')); if (dragIndex === dropIndex) return; const newSteps = [...summarizationSteps]; const [removed] = newSteps.splice(dragIndex, 1); newSteps.splice(dropIndex, 0, removed); setSummarizationSteps(newSteps.map((s, i) => ({ ...s, order: i }))); setDraggedStepIndex(null); };
    const moveStep = (index: number, direction: -1 | 1) => { const newIndex = index + direction; if (newIndex < 0 || newIndex >= summarizationSteps.length) return; const newSteps = [...summarizationSteps]; [newSteps[index], newSteps[newIndex]] = [newSteps[newIndex], newSteps[index]]; setSummarizationSteps(newSteps.map((s, i) => ({ ...s, order: i }))); };
    const updateStepField = <K extends keyof SummarizationStep>(index: number, field: K, value: SummarizationStep[K]) => { setSummarizationSteps(prev => prev.map((s, i) => i === index ? { ...s, [field]: value, lastUpdatedTimestamp: Date.now() } : s)); };
    const addSummarizationStep = (strategyType: SummarizationStrategyType) => {
        const now = Date.now();
        const newStep: SummarizationStep = { id: `step-${uuidv4()}`, name: strategyType, strategyType, enabled: true, order: summarizationSteps.length, summaryTokenBudget: 512, triggerTokenThreshold: 0, firstCreatedTimestamp: now, lastUpdatedTimestamp: now };
        if (strategyType === 'Sliding Window Replace') newStep.slidingWindowSize = 10;
        if (strategyType === 'Periodic Compression') { newStep.periodicCompressionInterval = 20; newStep.periodicCompressionChunkSize = 10; }
        if (strategyType === 'Recursive Summary') { newStep.recursiveSummaryChunkSize = 10; newStep.recursiveSummaryMaximumDepth = 3; }
        if (strategyType === 'Observation Masking') { newStep.maskingRelevanceThreshold = 0.3; newStep.maskingKeywordWeight = 0.7; }
        if (strategyType === 'Entropy Pruning') { 
            newStep.entropyPruningChunkSize = 3; 
            newStep.entropyPruningThreshold = 0.35; 
            newStep.entropyPruningTokenBudget = 2000; 
        }
        setSummarizationSteps(prev => [...prev, newStep]);
    };
    const removeSummarizationStep = (index: number) => { setSummarizationSteps(prev => prev.filter((_, i) => i !== index).map((s, i) => ({ ...s, order: i }))); if (expandedStepId === summarizationSteps[index]?.id) setExpandedStepId(null); };

    const renderOverrideSlider = (label: string, value: number, min: number, max: number, step: number, decimals: number, onChange: (val: number) => void, desc: string, valueLabel?: string) => (
        <div style={{ marginBottom: '12px' }}>
            <div style={SLIDER_HEADER_STYLE}><label className="editor-label editor-label-small" style={SLIDER_LABEL_STYLE}>{label}</label>{valueLabel && <span style={SLIDER_VALUE_STYLE}>{valueLabel}</span>}</div>
            <SliderInput label="" value={value} minimumValue={min} maximumValue={max} stepValue={step} decimals={decimals} onChange={onChange} description={desc} />
        </div>
    );

    const allToolKeys = Object.keys(toolLabels) as tool[];
    const narrateTextKeys = Object.keys(NARRATE_TEXT_LABELS) as textType[];

    const selectedToolDisplayMode = TOOL_USAGE_DISPLAY_MODES.find(m => m.value === toolUsageDisplayMode) ?? TOOL_USAGE_DISPLAY_MODES[0];

    // Filtered tools based on search query
    const filteredToolKeys = useMemo(() => {
        const q = toolSearchQuery.toLowerCase().trim();
        if (!q) return allToolKeys;
        return allToolKeys.filter(toolName => {
            const label = (toolLabels[toolName] ?? toolName).toLowerCase();
            return label.includes(q) || toolName.toLowerCase().includes(q);
        });
    }, [allToolKeys, toolSearchQuery]);

    const profileTabs: { id: ProfileTabId; label: string; icon: string }[] = [
        { id: 'general', label: 'General', icon: '📝' },
        { id: 'injection', label: 'Injection', icon: '💉' },
        { id: 'behaviour', label: 'Behaviour', icon: '🧠' },
        { id: 'tools', label: 'Tools', icon: '🔧' },
        { id: 'pipeline', label: 'Pipeline', icon: '🔄' },
        { id: 'cache', label: 'Cache', icon: '⚡' },
        { id: 'model', label: 'Model', icon: '🤖' },
    ];

    const cacheCategories: cacheEfficiencyConfigurationType[] = ['Character Name', 'System Prompt', 'Think Prompt'];

    return (
        <div className="modal-overlay" onClick={onClose}>
            <div className="modal-content editor-modal-content" onClick={e => e.stopPropagation()}>
                <div className="modal-header">
                    <h2>{ep ? 'Edit Profile' : 'Create New Profile'}</h2>
                    <div className="editor-modal-actions">
                        <button type="button" className="editor-button editor-button-cancel" onClick={onClose}>Cancel</button>
                        {ep && <button type="button" className="editor-button editor-button-cancel" onClick={handleClone}>Clone</button>}
                        <button type="button" className="editor-button editor-button-save" onClick={handleSubmit}>Save</button>
                    </div>
                </div>

                {/* Tab Bar */}
                <div className="entity-tab-bar" style={{ padding: '0 20px', marginBottom: 0, borderBottom: '1px solid var(--border)', background: 'var(--social-bg)' }}>
                    {profileTabs.map(tab => (
                        <button
                            key={tab.id}
                            type="button"
                            onClick={() => setActiveTab(tab.id)}
                            className={`entity-tab-button ${activeTab === tab.id ? 'entity-tab-button-active' : ''}`}
                        >
                            {tab.icon} {tab.label}
                        </button>
                    ))}
                </div>

                <div className="modal-body editor-modal-body">
                    {/* ─── GENERAL TAB ─── */}
                    {activeTab === 'general' && (
                        <>
                            <div style={{ marginBottom: '16px' }}><label className="editor-label">Name <span style={{ color: '#ff4444' }}>*</span></label><input type="text" value={name} onChange={(e) => { setName(e.target.value); if (errors.name) setErrors({ ...errors, name: undefined }); }} className={`editor-input ${errors.name ? 'error' : ''}`} placeholder="e.g., Default RP, No Cache Mode, Strict Names" />{errors.name && <div className="editor-error-message">{errors.name}</div>}</div>
                            <div style={{ marginBottom: '16px' }}><label className="editor-label">Description</label><textarea value={description} onChange={(e) => setDescription(e.target.value)} className="editor-textarea" placeholder="Describe when to use this profile" rows={2} /></div>

                            <div className="editor-section"><span className="editor-section-title">Agentic Roleplay</span><ProfileCheckbox checked={autonomousMode} onChange={setAutonomousMode} label="Autonomous Mode" hint="When enabled, characters act independently in the background using weighted sampling based on initiative, stamina ratios, and skip probability." />{autonomousMode && (<div style={{ marginTop: '12px' }}><div style={SLIDER_HEADER_STYLE}><label className="editor-label editor-label-small" style={SLIDER_LABEL_STYLE}>Interaction Interval</label><span style={SLIDER_VALUE_STYLE}>{(autonomousInteractionIntervalMs / 1000).toFixed(1)}s</span></div><SliderInput label="" value={autonomousInteractionIntervalMs} minimumValue={1000} maximumValue={60000} stepValue={1000} decimals={0} onChange={(val) => setAutonomousInteractionIntervalMs(Math.round(val))} description="How often the engine evaluates characters for autonomous actions. Lower = more frequent activity, higher token usage." /></div>)}</div>

                            <div className="editor-section">
                                <span className="editor-section-title">Volume</span>
                                <div style={{ marginBottom: '12px' }}>
                                    <div style={SLIDER_HEADER_STYLE}><label className="editor-label editor-label-small" style={SLIDER_LABEL_STYLE}>Global Volume Override</label><span style={SLIDER_VALUE_STYLE}>{volume === -1 ? '(Per-track default)' : `${Math.round(volume * 100)}%`}</span></div>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><input type="range" min="-1" max="1" step="0.01" value={volume} onChange={(e) => setVolume(Number(e.target.value))} style={{ flex: 1 }} /></div>
                                    <div style={FIELD_HINT_STYLE}>-1 = use each track's own volume. ≥0 = override all tracks uniformly.</div>
                                </div>
                            </div>

                            <div className="editor-section">
                                <span className="editor-section-title">Display</span>
                                <ProfileCheckbox checked={forceNameReveal} onChange={setForceNameReveal} label="Force Name Reveal" hint='Always show character names instead of "Character X".' />
                                <ProfileCheckbox checked={enableAmbientNarration} onChange={setEnableAmbientNarration} label="Enable Ambient Narration" hint="When no character responds, generate environmental/atmospheric narration to fill silence." spaced />
                                <div style={{ marginTop: '12px', marginBottom: '12px' }}>
                                    <label className="editor-label editor-label-small">Tool Usage Display Mode</label>
                                    <select value={toolUsageDisplayMode} onChange={(e) => setToolUsageDisplayMode(e.target.value as toolUsageDisplayMode)} className="editor-select" style={{ width: '100%' }}>
                                        {TOOL_USAGE_DISPLAY_MODES.map(mode => (<option key={mode.value} value={mode.value}>{mode.label}</option>))}
                                    </select>
                                    <div style={FIELD_HINT_STYLE}>{selectedToolDisplayMode.description}</div>
                                </div>
                                <ProfileCheckbox checked={enableCharacterExpression} onChange={setEnableCharacterExpression} label="Enable Character Expression" hint="Use sentiment analysis to swap character images based on emotional tone. Disable to always use the neutral character images." />
                            </div>

                            <div className="editor-section"><span className="editor-section-title">Voice Narration</span><div className="voice-narration-grid">{narrateTextKeys.map(type => (<label key={type} className="voice-narration-toggle"><input type="checkbox" checked={narrateTexts[type]} onChange={(e) => handleNarrateToggle(type, e.target.checked)} className="editor-checkbox-input" /><span>{NARRATE_TEXT_LABELS[type]}</span></label>))}</div></div>

                            <div className="editor-section"><span className="editor-section-title">Output Processing</span><ProfileCheckbox checked={stripThinkTokens} onChange={setStripThinkTokens} label="Strip Think Tokens" hint="Remove thinking tokens from displayed output. The model still uses them internally." /></div>
                        </>
                    )}

                    {/* ─── INJECTION TAB ─── */}
                    {activeTab === 'injection' && (
                        <>
                            <div className="editor-section">
                                <span className="editor-section-title">Text Character Injection</span>
                                <ProfileCheckbox checked={randomizeTextCharacterInjection} onChange={setRandomizeTextCharacterInjection} label="Randomize Text Character Injection" hint="Prepend randomized characters from each character's text injection pool to bypass provider input filters that reject certain prompt patterns." />
                                {randomizeTextCharacterInjection && (
                                    <>
                                        <ProfileCheckbox checked={randomizeTextCharacterInjectionOnRetry} onChange={setRandomizeTextCharacterInjectionOnRetry} label="Only Randomize On Retry" hint="Only apply randomization if the initial generation fails. Reduces unnecessary randomization when the model accepts the prompt as-is." spaced />
                                        <div style={{ marginTop: '12px' }}>
                                            <SliderInput label="Maximum Number Of Text Character Randomization Per Model" value={maximumNumberOfTextCharacterRandomizationPerModel} minimumValue={1} maximumValue={10} stepValue={1} decimals={0} onChange={(val) => setMaximumNumberOfTextCharacterRandomizationPerModel(Math.round(val))} description="Number of retry attempts per model before giving up on randomization. Higher = more chances to bypass filters but uses more tokens." />
                                        </div>
                                    </>
                                )}
                            </div>

                            <div className="editor-section">
                                <span className="editor-section-title">Image Injection</span>
                                <ProfileCheckbox checked={forceNoCharacterImageInjection} onChange={setForceNoCharacterImageInjection} label="Force No Character Image Injection" hint="Prevent character images from being sent to the model, even if the character has one assigned." />
                                <ProfileCheckbox checked={forceNoContextImageInjection} onChange={setForceNoContextImageInjection} label="Force No Context Image Injection" hint="Prevent context images from being sent to the model." spaced />
                                <ProfileCheckbox checked={forceNoLocationImageInjection} onChange={setForceNoLocationImageInjection} label="Force No Location Image Injection" hint="Prevent location images from being sent to the model." spaced />
                            </div>

                            <div className="editor-section">
                                <span className="editor-section-title">Context Injection</span>
                                <div style={{ marginBottom: '12px' }}>
                                    <label className="editor-label editor-label-small">OpenWeather API Key</label>
                                    <input type="password" value={weatherApiKey} onChange={(e) => setWeatherApiKey(e.target.value)} className="editor-input" placeholder="Paste your OpenWeather API key..." autoComplete="off" />
                                    <div style={FIELD_HINT_STYLE}>Free tier: 1,000 calls/day. Get one at openweathermap.org/api</div>
                                </div>
                                <div style={{ marginTop: '12px' }}>{renderOverrideSlider('Use Front Camera Image Override', useFrontCameraImage, -1, 1, 1, 0, (val) => setUseFrontCameraImage(Math.round(val) as tristateInteger), 'Replace protagonist stored image with live front camera snapshot. Camera activates on first use and auto-closes after 10 minutes idle.', useFrontCameraImage === -1 ? '(Force Off)' : useFrontCameraImage === 1 ? '(Force On)' : '(Per-Character default)')}</div>
                            </div>

                            <div className="editor-section">
                                <span className="editor-section-title">Prompt Decay</span>
                                <div style={{ fontSize: '0.6rem', opacity: 0.5, marginBottom: '12px' }}>Prompts are automatically removed from context after the character has sent this many messages. Set to 0 to disable immediately, or leave high to keep them active longer.</div>
                                <SliderInput label="Number of Messages to Disable Think Prompt" value={numberOfMessagesToDisableThinkPrompt} minimumValue={-1} maximumValue={10} stepValue={1} decimals={0} onChange={(val) => setNumberOfMessagesToDisableThinkPrompt(Math.round(val))} description="-1 = auto defer to character default. N = disable after N messages." />
                                <div style={{ marginTop: '12px' }}><SliderInput label="Number of Messages to Disable Meta-Thinking" value={numberOfMessagesToDisableMetaThinkInstructions} minimumValue={-1} maximumValue={10} stepValue={1} decimals={0} onChange={(val) => setNumberOfMessagesToDisableMetaThinkInstructions(Math.round(val))} description="-1 = auto defer to character default. N = disable after N messages." /></div>
                                <div style={{ marginTop: '12px' }}><SliderInput label="Number of Messages to Disable Dialogue Prompt" value={numberOfMessagesToDisableDialoguePrompt} minimumValue={-1} maximumValue={10} stepValue={1} decimals={0} onChange={(val) => setNumberOfMessagesToDisableDialoguePrompt(Math.round(val))} description="-1 = auto defer to character default. N = disable after N messages." /></div>
                                <div style={{ marginTop: '12px' }}><SliderInput label="Number of Messages to Disable Starter Prompt" value={numberOfMessagesToDisableStarterPrompt} minimumValue={-1} maximumValue={10} stepValue={1} decimals={0} onChange={(val) => setNumberOfMessagesToDisableStarterPrompt(Math.round(val))} description="-1 = auto defer to character default. N = disable after N messages." /></div>
                            </div>
                        </>
                    )}

                    {/* ─── BEHAVIOUR TAB ─── */}
                    {activeTab === 'behaviour' && (
                        <div className="editor-section">
                            <span className="editor-section-title">Turn Sequencing</span>
                            <div style={{ ...CHECKBOX_HINT_STYLE, marginLeft: 0, marginBottom: '12px' }}>-1 = defer to each character's own setting. Set a value to override all participants uniformly.</div>
                            <ProfileCheckbox checked={forceEqualInitiative} onChange={setForceEqualInitiative} label="Force Equal Initiative" hint="All participants get equal initiative weight regardless of character settings." />
                            {renderOverrideSlider('Chat Probability Override', chatProbability, -1, 1, 0.05, 2, setChatProbability, 'Probability of initiating a chat message when selected.', chatProbability === -1 ? '(Character default)' : undefined)}
                            {renderOverrideSlider('Maximum Chat Stamina Override', maximumChatStamina, -1, 10, 1, 0, (val) => setMaximumChatStamina(Math.round(val)), 'Maximum paragraphs the character can produce.', maximumChatStamina === -1 ? '(Character default)' : undefined)}
                            {renderOverrideSlider('Name Sensitivity Override', nameSensitivity, -1, 10, 0.5, 1, setNameSensitivity, 'Multiplier per name mention in latest message. 0 = off.', nameSensitivity === -1 ? '(Character default)' : nameSensitivity === 0 ? '(Disabled)' : undefined)}
                            {renderOverrideSlider('Skip Probability Override', skipProbability, -1, 1, 0.05, 2, setSkipProbability, 'Probability of skipping an action even when selected.', skipProbability === -1 ? '(Character default)' : skipProbability === 0 ? '(Disabled)' : undefined)}
                            {renderOverrideSlider('Chat Impatience Override', chatImpatienceSensitivity, -1, 5, 0.1, 1, setChatImpatienceSensitivity, 'Higher values make quiet characters speak sooner. 0 = off.', chatImpatienceSensitivity === -1 ? '(Character default)' : chatImpatienceSensitivity === 0 ? '(Disabled)' : undefined)}
                            {renderOverrideSlider('Memory Retention Override', memoryRetentionWeight, -1, 2, 0.1, 1, setMemoryRetentionWeight, 'How far back memories reach. 0 = minimal, 1 = full.', memoryRetentionWeight === -1 ? '(Character default)' : memoryRetentionWeight === 0 ? '(Minimal)' : undefined)}
                            {renderOverrideSlider('Context Sensitivity Override', contextSensitivity, -1, 2, 0.1, 1, setContextSensitivity, 'How readily context entries trigger. 0 = never.', contextSensitivity === -1 ? '(Character default)' : contextSensitivity === 0 ? '(Blind)' : undefined)}
                            {renderOverrideSlider('Maximum Action Stamina Override', maximumActionStamina, -1, 10, 1, 0, (val) => setMaximumActionStamina(Math.round(val)), 'Silent actions (movement, non-chat interactions) before needing rest.', maximumActionStamina === -1 ? '(Character default)' : undefined)}
                        </div>
                    )}

                    {/* ─── TOOLS TAB ─── */}
                    {activeTab === 'tools' && (
                        <div className="editor-section">
                            <span className="editor-section-title">Tools</span>
                            <div style={{ ...CHECKBOX_HINT_STYLE, marginLeft: 0, marginBottom: '8px' }}>-1 = force off for all characters. 0 = defer to each character's own setting. 1 = force on for all characters.</div>

                            <div style={{ display: 'flex', gap: '6px', marginBottom: '12px' }}>
                                <button
                                    type="button"
                                    className="toolbar-button"
                                    onClick={handleSelectAllTools}
                                    style={{ flex: 1, fontSize: '0.7rem', padding: '4px 8px' }}
                                >
                                    Force All On
                                </button>
                                <button
                                    type="button"
                                    className="toolbar-button"
                                    onClick={handleResetToolsToDefaults}
                                    style={{ flex: 1, fontSize: '0.7rem', padding: '4px 8px' }}
                                >
                                    Reset to Defaults
                                </button>
                                <button
                                    type="button"
                                    className="toolbar-button"
                                    onClick={handleDeselectAllTools}
                                    style={{ flex: 1, fontSize: '0.7rem', padding: '4px 8px' }}
                                >
                                    Force All Off
                                </button>
                            </div>

                            <input
                                type="text"
                                value={toolSearchQuery}
                                onChange={e => setToolSearchQuery(e.target.value)}
                                className="editor-input"
                                placeholder="Search tools..."
                                style={{ marginBottom: '12px', fontSize: '0.75rem', padding: '6px 10px' }}
                            />

                            {filteredToolKeys.length === 0 && (
                                <div style={{ fontSize: '0.7rem', opacity: 0.5, fontStyle: 'italic', padding: '8px 0' }}>
                                    No tools match "{toolSearchQuery}".
                                </div>
                            )}

                            {filteredToolKeys.map(toolName => (<div key={toolName} style={{ marginBottom: '12px' }}><div style={SLIDER_HEADER_STYLE}><label className="editor-label editor-label-small" style={SLIDER_LABEL_STYLE}>{toolLabels[toolName]} Override</label><span style={SLIDER_VALUE_STYLE}>{tools[toolName] === -1 ? '(Force Off)' : tools[toolName] === 1 ? '(Force On)' : '(Character default)'}</span></div><SliderInput label="" value={tools[toolName]} minimumValue={-1} maximumValue={1} stepValue={1} decimals={0} onChange={(val) => handleToolChange(toolName, Math.round(val) as tristateInteger)} description="" /></div>))}
                        </div>
                    )}

                    {/* ─── PIPELINE TAB ─── */}
                    {activeTab === 'pipeline' && (
                        <>
                            <div className="editor-section">
                                <div className="editor-section-title" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span>Prompt Block Order</span><span style={{ fontSize: '0.6rem', opacity: 0.5, fontWeight: 'normal', textTransform: 'none', letterSpacing: 0 }}>↕ Drag To Reorder</span></div>
                                <div style={CHECKBOX_HINT_STYLE}>Controls the order in which prompt sections are assembled. Includes built-in blocks and custom prompt blocks.</div>
                                <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>{inputStrategy.map((blockEntry, index) => (<div key={`${blockEntry}-${index}`} draggable onDragStart={(e) => handleDragStart(e, index)} onDragEnd={handleDragEnd} onDragOver={handleDragOver} onDrop={(e) => handleDrop(e, index)} className={`sampler-param-row ${draggedIndex === index ? 'sampler-param-dragging' : ''}`} style={{ padding: '6px 8px' }}><div className="sampler-drag-handle" title="Drag to reorder">⋮⋮</div><div style={{ flex: 1, minWidth: 0, display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ fontSize: '0.75rem', fontWeight: 'bold', color: 'var(--text-h)' }}>{index + 1}. {getBlockLabel(blockEntry)}</span></div><div style={{ display: 'flex', gap: '2px', alignItems: 'center', flexShrink: 0 }}><button type="button" onClick={() => moveBlock(index, -1)} disabled={index === 0} className="toolbar-button" title="Move up" style={{ ...TOOLBAR_BTN_SMALL_STYLE, opacity: index === 0 ? 0.3 : 1 }}>▲</button><button type="button" onClick={() => moveBlock(index, 1)} disabled={index === inputStrategy.length - 1} className="toolbar-button" title="Move down" style={{ ...TOOLBAR_BTN_SMALL_STYLE, opacity: index === inputStrategy.length - 1 ? 0.3 : 1 }}>▼</button><button type="button" onClick={() => removeBlock(index)} className="toolbar-button" title="Remove from order" style={TOOLBAR_BTN_DELETE_STYLE}>×</button></div></div>))}</div>
                                {(missingBuiltInBlocks.length > 0 || availablePromptBlocks.length > 0) && (<div style={{ marginTop: '8px', display: 'flex', gap: '4px', flexWrap: 'wrap' }}><select onChange={(e) => { const val = e.target.value; if (val) addBlock(val); e.target.value = ''; }} className="editor-select" defaultValue="" style={{ flex: 1 }}><option value="" disabled>+ Add a block</option>{missingBuiltInBlocks.length > 0 && <optgroup label="Built-in Blocks">{missingBuiltInBlocks.map(b => <option key={b} value={b}>{b}</option>)}</optgroup>}{availablePromptBlocks.length > 0 && <optgroup label="Custom Prompt Blocks">{availablePromptBlocks.map((pb: PromptBlock) => <option key={pb.id} value={pb.id}>🧱 {pb.name}</option>)}</optgroup>}</select></div>)}
                            </div>

                            <div className="editor-section">
                                <div className="editor-section-title" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span>Summarization Pipeline</span><span style={{ fontSize: '0.6rem', opacity: 0.5, fontWeight: 'normal', textTransform: 'none', letterSpacing: 0 }}>↕ Drag To Reorder</span></div>
                                <div style={CHECKBOX_HINT_STYLE}>Controls how messages are summarized based on the order of the individual text summarizers.</div>
                                <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>{summarizationSteps.map((step, index) => { const isDragging = draggedStepIndex === index; const isExpanded = expandedStepId === step.id; return (<div key={step.id}><div draggable onDragStart={(e) => handleStepDragStart(e, index)} onDragEnd={handleStepDragEnd} onDragOver={handleDragOver} onDrop={(e) => handleStepDrop(e, index)} className={`sampler-param-row ${isDragging ? 'sampler-param-dragging' : ''}`} style={{ padding: '6px 8px', cursor: 'pointer' }} onClick={() => setExpandedStepId(isExpanded ? null : step.id)}><div className="sampler-drag-handle" title="Drag to reorder" onClick={(e) => e.stopPropagation()}>⋮⋮</div><div style={{ flex: 1, minWidth: 0, display: 'flex', alignItems: 'center', gap: '8px' }}><span style={STEP_NAME_STYLE}>{index + 1}. {step.name}</span></div><div style={{ display: 'flex', gap: '2px', alignItems: 'center', flexShrink: 0 }} onClick={(e) => e.stopPropagation()}><button type="button" onClick={() => moveStep(index, -1)} disabled={index === 0} className="toolbar-button" title="Move up" style={{ ...TOOLBAR_BTN_SMALL_STYLE, opacity: index === 0 ? 0.3 : 1 }}>▲</button><button type="button" onClick={() => moveStep(index, 1)} disabled={index === summarizationSteps.length - 1} className="toolbar-button" title="Move down" style={{ ...TOOLBAR_BTN_SMALL_STYLE, opacity: index === summarizationSteps.length - 1 ? 0.3 : 1 }}>▼</button><button type="button" onClick={() => removeSummarizationStep(index)} className="toolbar-button" title="Remove step" style={TOOLBAR_BTN_DELETE_STYLE}>×</button><span style={{ fontSize: '0.7rem', opacity: 0.5, transition: 'transform 0.2s', transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)' }}>▼</span></div></div>{isExpanded && (<div style={STEP_EXPANDED_STYLE}><div style={STEP_DESC_STYLE}>{STRATEGY_DESCRIPTIONS[step.strategyType]}</div>{step.strategyType === 'Sliding Window Replace' && (<div><label className="editor-label editor-label-small">Window Size</label><input type="number" min="1" max="50" value={step.slidingWindowSize ?? 10} onChange={(e) => updateStepField(index, 'slidingWindowSize', Math.max(1, Number(e.target.value) || 10))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Keep last N messages verbatim</div></div>)}{step.strategyType === 'Periodic Compression' && (<div className="editor-row"><div><label className="editor-label editor-label-small">Compression Interval</label><input type="number" min="5" max="100" value={step.periodicCompressionInterval ?? 20} onChange={(e) => updateStepField(index, 'periodicCompressionInterval', Math.max(5, Number(e.target.value) || 20))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Compress every M messages</div></div><div><label className="editor-label editor-label-small">Chunk Size</label><input type="number" min="5" max="50" value={step.periodicCompressionChunkSize ?? 10} onChange={(e) => updateStepField(index, 'periodicCompressionChunkSize', Math.max(5, Number(e.target.value) || 10))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Messages per compression chunk</div></div></div>)}{step.strategyType === 'Recursive Summary' && (<div className="editor-row"><div><label className="editor-label editor-label-small">Chunk Size</label><input type="number" min="5" max="50" value={step.recursiveSummaryChunkSize ?? 10} onChange={(e) => updateStepField(index, 'recursiveSummaryChunkSize', Math.max(5, Number(e.target.value) || 10))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Messages per chunk at layer 0</div></div><div><label className="editor-label editor-label-small">Max Depth</label><input type="number" min="1" max="5" value={step.recursiveSummaryMaximumDepth ?? 3} onChange={(e) => updateStepField(index, 'recursiveSummaryMaximumDepth', Math.max(1, Number(e.target.value) || 3))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Max recursion layers</div></div></div>)}{step.strategyType === 'Observation Masking' && (<div className="editor-row"><div><label className="editor-label editor-label-small">Relevance Threshold</label><input type="number" min="0" max="1" step="0.05" value={step.maskingRelevanceThreshold ?? 0.3} onChange={(e) => updateStepField(index, 'maskingRelevanceThreshold', Math.max(0, Math.min(1, Number(e.target.value) || 0.3)))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Min score to include (0.0–1.0)</div></div><div><label className="editor-label editor-label-small">Keyword Weight</label><input type="number" min="0" max="1" step="0.05" value={step.maskingKeywordWeight ?? 0.7} onChange={(e) => updateStepField(index, 'maskingKeywordWeight', Math.max(0, Math.min(1, Number(e.target.value) || 0.7)))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Keyword vs recency balance</div></div></div>)}{step.strategyType === 'Entropy Pruning' && (<div className="editor-row"><div><label className="editor-label editor-label-small">Chunk Size</label><input type="number" min="2" max="10" value={step.entropyPruningChunkSize ?? 3} onChange={(e) => updateStepField(index, 'entropyPruningChunkSize', Math.max(2, Number(e.target.value) || 3))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Messages per analysis unit</div></div><div><label className="editor-label editor-label-small">Entropy Threshold</label><input type="number" min="0" max="1" step="0.05" value={step.entropyPruningThreshold ?? 0.35} onChange={(e) => updateStepField(index, 'entropyPruningThreshold', Math.max(0, Math.min(1, Number(e.target.value) || 0.35)))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Below this = fluff (0.0–1.0)</div></div></div>)}{step.strategyType === 'Entropy Pruning' && (<div className="editor-row"><div><label className="editor-label editor-label-small">Raw Token Budget</label><input type="number" min="512" max="8192" step="256" value={step.entropyPruningTokenBudget ?? 2000} onChange={(e) => updateStepField(index, 'entropyPruningTokenBudget', Math.max(512, Number(e.target.value) || 2000))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Max tokens to keep raw before summarizing</div></div><div></div></div>)}<div className="editor-row"><div><label className="editor-label editor-label-small">Summary Token Budget</label><input type="number" min="64" max="4096" step="64" value={step.summaryTokenBudget ?? 512} onChange={(e) => updateStepField(index, 'summaryTokenBudget', Math.max(64, Number(e.target.value) || 512))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>Max tokens for generated summaries</div></div><div><label className="editor-label editor-label-small">Trigger Threshold</label><input type="number" min="0" max="131072" step="1024" value={step.triggerTokenThreshold ?? 0} onChange={(e) => updateStepField(index, 'triggerTokenThreshold', Math.max(0, Number(e.target.value) || 0))} className="editor-input" style={INPUT_RIGHT_STYLE} /><div style={FIELD_HINT_STYLE}>0 = auto based on context length</div></div></div></div>)}</div>); })}</div>
                                <div style={{ marginTop: '8px' }}><select onChange={(e) => { const val = e.target.value as SummarizationStrategyType; if (val) addSummarizationStep(val); e.target.value = ''; }} className="editor-select" defaultValue=""><option value="" disabled>+ Add a summarization step</option>{ALL_STRATEGY_TYPES.map(t => <option key={t} value={t}>{t}</option>)}</select></div>
                                {summarizationSteps.length === 0 && (<div style={{ fontSize: '0.75rem', opacity: 0.5, fontStyle: 'italic', textAlign: 'center', padding: '12px 0' }}>No summarization steps configured. Add one above to enable context management.</div>)}
                                
                                {/* Summarization Instruction Input */}
                                <div style={{ marginTop: '16px' }}>
                                    <label className="editor-label editor-label-small">Summarization Instruction</label>
                                    <textarea 
                                        value={summarizationInstruction} 
                                        onChange={(e) => setSummarizationInstruction(e.target.value)} 
                                        className="editor-textarea" 
                                        placeholder="Custom instruction for the summarization model. Leave empty to use system default."
                                        rows={3}
                                    />
                                    <div style={FIELD_HINT_STYLE}>If empty, the system will use the built-in default summarization instruction.</div>
                                </div>
                            </div>
                        </>
                    )}

                    {/* ─── CACHE TAB ─── */}
                    {activeTab === 'cache' && (
                        <>
                            <div className="editor-section">
                                <span className="editor-section-title">Cache Efficiency Levels</span>
                                <div style={{ fontSize: '0.6rem', opacity: 0.5, marginBottom: '12px' }}>
                                    Control how much participant content is frozen into the static prompt prefix for provider-side caching. Each category is independent. Higher levels improve cache hit rates at the cost of including more content upfront.
                                </div>
                                {cacheCategories.map(category => (
                                    <div key={category} style={{ marginBottom: '16px' }}>
                                        <div style={SLIDER_HEADER_STYLE}>
                                            <label className="editor-label editor-label-small" style={SLIDER_LABEL_STYLE}>{category}</label>
                                            <span style={SLIDER_VALUE_STYLE}>
                                                {cacheEfficiencyLevels[category] === 0 ? '(No optimization)' : cacheEfficiencyLevels[category] === 1 ? '(Co-located only)' : '(All participants)'}
                                            </span>
                                        </div>
                                        <SliderInput
                                            label=""
                                            value={cacheEfficiencyLevels[category]}
                                            minimumValue={0}
                                            maximumValue={2}
                                            stepValue={1}
                                            decimals={0}
                                            onChange={(val) => handleCacheLevelChange(category, val)}
                                            description={CACHE_EFFICIENCY_DESCRIPTIONS[category][Math.round(cacheEfficiencyLevels[category])] || ''}
                                        />
                                    </div>
                                ))}
                            </div>

                            <div className="editor-section">
                                <span className="editor-section-title">Volatile Section Ordering</span>
                                <ProfileCheckbox
                                    checked={minimalVolatileCacheMode}
                                    onChange={setMinimalVolatileCacheMode}
                                    label="Minimal Volatile Cache Mode"
                                    hint="When enabled, volatile sections (date/time, weather, fatigue, inventory, tools, location) are forced to the end of the prompt regardless of input strategy ordering. This maximizes the stable prefix for provider-side caching. When disabled, your configured prompt block order is respected exactly as-is."
                                />
                            </div>
                        </>
                    )}

                    {/* ─── MODEL TAB ─── */}
                    {activeTab === 'model' && (
                        <>
                            <div className="editor-section">
                                <span className="editor-section-title">Language Model Handling</span>
                                <ProfileCheckbox 
                                    checked={enableSpeculativeMarkov} 
                                    onChange={setEnableSpeculativeMarkov} 
                                    label="Enable Speculative Markov" 
                                    hint="Uses a local Markov chain trained on each character's own message history to predict and append highly confident tokens during streaming, reducing API output costs and perceived latency and may impact reasoning. Only aborts and resumes the stream when token savings exceed the network latency penalty." 
                                />
                                <ProfileCheckbox 
                                    checked={doNotInjectDefaultStopTokens} 
                                    onChange={setDoNotInjectDefaultStopTokens} 
                                    label="Do Not Inject Default Stop Tokens" 
                                    hint="Prevent default stop tokens from being injected into the request. Only custom stop patterns will be used." 
                                    spaced 
                                />
                            </div>

                            {/* ─── AUTO-RESUME SIGNALS SECTION ─── */}
                            <div className="editor-section">
                                <div className="sampler-section-header">
                                    <span className="editor-section-title" style={{ marginBottom: 0 }}>Auto-Resume Signals</span>
                                    <button 
                                        type="button" 
                                        className="editor-button editor-button-save" 
                                        onClick={handleAddAutoResumeSignal} 
                                        style={{ fontSize: '0.65rem', padding: '4px 12px', minHeight: '28px', height: '28px' }}
                                    >
                                        + Add Signal
                                    </button>
                                </div>
                                <div style={{ ...CHECKBOX_HINT_STYLE, marginLeft: 0, marginBottom: '8px' }}>
                                    Forces the model to continue generating if the output stops prematurely. Injects the stop pattern dynamically to steer the completion.
                                </div>

                                <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', marginTop: '8px' }}>
                                    {autoResumeSignals.map((signal, index) => {
                                        const isExpanded = expandedSignalIndex === index;
                                        const signalName = signal.stopPattern || '(No Stop Pattern Set)';
                                        
                                        return (
                                            <div key={index}>
                                                <div 
                                                    className="sampler-param-row" 
                                                    style={{ padding: '6px 8px', cursor: 'pointer' }} 
                                                    onClick={() => setExpandedSignalIndex(isExpanded ? null : index)}
                                                >
                                                    <div style={{ flex: 1, minWidth: 0, display: 'flex', alignItems: 'center', gap: '8px' }}>
                                                        <span style={STEP_NAME_STYLE}>
                                                            {index + 1}. {signalName}
                                                        </span>
                                                        {signal.regularExpressionActivationTrigger && (
                                                            <span style={{ fontSize: '0.6rem', opacity: 0.6, background: 'var(--code-bg)', padding: '1px 4px', borderRadius: '3px' }}>Regex</span>
                                                        )}
                                                    </div>
                                                    <div style={{ display: 'flex', gap: '2px', alignItems: 'center', flexShrink: 0 }} onClick={(e) => e.stopPropagation()}>
                                                        <span style={{ fontSize: '0.65rem', opacity: 0.6, marginRight: '4px' }}>
                                                            Maximum Auto-Resumes: {signal.maximumNumberOfAutoResumes ?? 10}
                                                        </span>
                                                        <button 
                                                            type="button" 
                                                            onClick={() => handleRemoveAutoResumeSignal(index)} 
                                                            className="toolbar-button" 
                                                            title="Remove signal" 
                                                            style={TOOLBAR_BTN_DELETE_STYLE}
                                                        >×</button>
                                                        <span style={{ fontSize: '0.7rem', opacity: 0.5, transition: 'transform 0.2s', transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)' }}>▼</span>
                                                    </div>
                                                </div>
                                                
                                                {isExpanded && (
                                                    <div style={STEP_EXPANDED_STYLE}>
                                                        <div className="editor-row">
                                                            <div>
                                                                <label className="editor-label editor-label-small">Activation Trigger (Regex)</label>
                                                                <input
                                                                    type="text"
                                                                    value={signal.regularExpressionActivationTrigger || ''}
                                                                    onChange={(e) => handleUpdateAutoResumeSignal(index, 'regularExpressionActivationTrigger', e.target.value)}
                                                                    className="editor-input"
                                                                    placeholder="e.g., \[Thinking\]"
                                                                />
                                                                <div style={FIELD_HINT_STYLE}>Optional. Activates auto-resume if matched.</div>
                                                            </div>
                                                            <div>
                                                                <label className="editor-label editor-label-small">Deactivation Trigger (Regex)</label>
                                                                <input
                                                                    type="text"
                                                                    value={signal.regularExpressionDeactivationTrigger || ''}
                                                                    onChange={(e) => handleUpdateAutoResumeSignal(index, 'regularExpressionDeactivationTrigger', e.target.value)}
                                                                    className="editor-input"
                                                                    placeholder="e.g., \[End\]"
                                                                />
                                                                <div style={FIELD_HINT_STYLE}>Optional. Deactivates auto-resume if matched.</div>
                                                            </div>
                                                        </div>
                                                        
                                                        <div className="editor-row">
                                                            <div>
                                                                <label className="editor-label editor-label-small">Stop Pattern *</label>
                                                                <input
                                                                    type="text"
                                                                    value={signal.stopPattern}
                                                                    onChange={(e) => handleUpdateAutoResumeSignal(index, 'stopPattern', e.target.value)}
                                                                    className="editor-input"
                                                                    placeholder="e.g., \n\n"
                                                                />
                                                                <div style={FIELD_HINT_STYLE}>Appended to sampler stop patterns if activated.</div>
                                                            </div>
                                                            <div>
                                                                <label className="editor-label editor-label-small">Minimum Length</label>
                                                                <input
                                                                    type="text"
                                                                    value={signal.minimumLength || '0'}
                                                                    onChange={(e) => handleUpdateAutoResumeSignal(index, 'minimumLength', e.target.value)}
                                                                    className="editor-input"
                                                                    placeholder="0"
                                                                />
                                                                <div style={FIELD_HINT_STYLE}>Min characters after activation before deactivation.</div>
                                                            </div>
                                                        </div>

                                                        <div className="editor-row">
                                                            <div>
                                                                <label className="editor-label editor-label-small">Maximum Number Of Auto-Resumes</label>
                                                                <input
                                                                    type="number"
                                                                    value={signal.maximumNumberOfAutoResumes ?? 10}
                                                                    onChange={(e) => handleUpdateAutoResumeSignal(index, 'maximumNumberOfAutoResumes', e.target.value)}
                                                                    className="editor-input"
                                                                    placeholder="10"
                                                                    min="0"
                                                                />
                                                                <div style={FIELD_HINT_STYLE}>0 = disabled. Default is 10.</div>
                                                            </div>
                                                            <div></div>
                                                        </div>
                                                    </div>
                                                )}
                                            </div>
                                        );
                                    })}
                                    
                                    {autoResumeSignals.length === 0 && (
                                        <div style={{ fontSize: '0.75rem', opacity: 0.5, fontStyle: 'italic', textAlign: 'center', padding: '12px 0' }}>
                                            No auto-resume signals configured. The model will rely entirely on natural stop sequences.
                                        </div>
                                    )}
                                </div>
                            </div>
                            {/* ───────────────────────────────────────── */}

                            <div className="editor-section">
                                <span className="editor-section-title">Samplers</span>
                                <div style={CHECKBOX_HINT_STYLE}>Assign specific samplers for different generation tasks. Leave empty to use system defaults.</div>
                                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '12px', marginTop: '12px' }}>
                                    <div><label className="editor-label editor-label-small">Character Sampler</label><select value={characterSamplerId} onChange={(e) => setCharacterSamplerId(e.target.value)} className="editor-select"><option value="">(System Default)</option>{allSamplers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><div style={FIELD_HINT_STYLE}>Used for main character dialogue/actions.</div></div>
                                    <div><label className="editor-label editor-label-small">Web Summarization Sampler</label><select value={webSummarizationSamplerId} onChange={(e) => setWebSummarizationSamplerId(e.target.value)} className="editor-select"><option value="">(System Default)</option>{allSamplers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><div style={FIELD_HINT_STYLE}>Used for summarizing web search results.</div></div>
                                    <div><label className="editor-label editor-label-small">Interaction Data Sampler</label><select value={interactionDataSummarizationSamplerId} onChange={(e) => setInteractionDataSummarizationSamplerId(e.target.value)} className="editor-select"><option value="">(System Default)</option>{allSamplers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><div style={FIELD_HINT_STYLE}>Used for summarizing chat history/context.</div></div>
                                    <div><label className="editor-label editor-label-small">AI Recommendation Sampler</label><select value={aiRecommendationSamplerId} onChange={(e) => setAiRecommendationSamplerId(e.target.value)} className="editor-select"><option value="">(System Default)</option>{allSamplers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><div style={FIELD_HINT_STYLE}>Used for AI recommendation generations.</div></div>
                                </div>
                            </div>

                            <div className="editor-section">
                                <span className="editor-section-title">Stop Patterns</span>
                                <div style={CHECKBOX_HINT_STYLE}>Assign specific stop patterns for different generation tasks. Leave empty to use sampler defaults.</div>
                                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '12px', marginTop: '12px' }}>
                                    <StopPatternSelect label="Character Stop Pattern" value={characterStopPatternId} onChange={setCharacterStopPatternId} allStopPatterns={allStopPatterns} />
                                    <StopPatternSelect label="Web Summarization Stop Pattern" value={webSummarizationStopPatternId} onChange={setWebSummarizationStopPatternId} allStopPatterns={allStopPatterns} />
                                    <StopPatternSelect label="Interaction Data Stop Pattern" value={interactionDataSummarizationStopPatternId} onChange={setInteractionDataSummarizationStopPatternId} allStopPatterns={allStopPatterns} />
                                    <StopPatternSelect label="AI Recommendation Stop Pattern" value={aiRecommendationStopPatternId} onChange={setAiRecommendationStopPatternId} allStopPatterns={allStopPatterns} />
                                </div>
                            </div>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
}