// src/types.ts

export type tristateInteger = -1 | 0 | 1

export type regularExpressionContext = 'global' | 'local' | 'previous';

export type regularExpressionTarget = 'everyone' | 'listener' | 'self' | 'protagonist' | 'narrator';
export interface ObjectData {
  id: string;
  name: string;
  description?: string;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;
}

export interface RawData {
  id?: string;
  name: string;
  description?: string;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;
}

export interface RegularExpressionTrigger {
  trigger: string
  context: regularExpressionContext
  target: regularExpressionTarget
}

export interface StopPattern extends ObjectData {
  pattern: string;
  regularExpressionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
}

export interface RawStopPattern extends RawData {
  pattern: string;
  regularExpressionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
}

export interface Sampler extends ObjectData {
  parameters?: Record<string, unknown>;
  stopPatterns: StopPattern[];
  maximumNumberOfTokens?: number;
}

export interface RawSampler extends RawData {
  parameters?: Record<string, unknown>;
  stopPatternIds: string[];
  maximumNumberOfTokens?: number;
}

export type searchEngine = "Google" | "Bing" | "DuckDuckGo" | "Yandex" | "Baidu";

export type linkFetchMode = 'full' | 'summary' | 'extract'

export interface Context extends ObjectData {
  text?: string;
  images?: string[];
  searchTerms?: string[];
  searchEngine?: searchEngine;
  urls?: string[];
  includeLinkImages?: boolean;
  maximumLinkDepth?: number;
  linkFetchMode?: linkFetchMode;
  limitLinksToSubdirectory: boolean;
  fetchCacheTimeToLiveMs?: number;
  regularExpressionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  tokenBudget?: number;
  maximumRecursionDepth?: number;
  insertionDepth?: number;
  characterBindings?: string[];
  useBase64Encoding: boolean;
  isAutoGenerated?: boolean;
}

export interface RawContext extends RawData {
  text?: string;
  images?: string[];
  searchTerms?: string[];
  searchEngine?: searchEngine;
  urls?: string[];
  includeLinkImages?: boolean;
  maximumLinkDepth?: number;
  linkFetchMode?: linkFetchMode;
  limitLinksToSubdirectory: boolean;
  fetchCacheTimeToLiveMs?: number;
  regularExpressionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  tokenBudget?: number;
  maximumRecursionDepth?: number;
  insertionDepth?: number;
  characterBindings?: string[];
  useBase64Encoding: boolean;
  isAutoGenerated?: boolean;
}

export interface Location extends ObjectData {
  text?: string;
  images?: string[];
  regularExpressionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  backgroundImageRegularExpressionActivationTriggers?: Record<number, string>
  backgroundImageWeights?: Record<number, number>
  playAudioTrackOnEnterWeights?: Record<string, number>;
  locationBindings?: string[]; // Accessible to target X from current location Y.
  locationBindingRegularExpressionTriggers?: Record<string, string>
  characterBindings?: string[];
  globalWeight?: number;
  characterWeights?: Record<string, number>;
  ownerBindings?: string[]
  latitude?: number;
  longitude?: number;
  locationDistances?: Record<string, number>;
  messageFilterNonCoLocatedParticipants?: boolean;
  messageFilterRegularExpressionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  useBase64Encoding?: boolean;
}

export interface RawLocation extends RawData {
  text?: string;
  images?: string[];
  regularExpressionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  backgroundImageRegularExpressionActivationTriggers?: Record<number, string>
  backgroundImageWeights?: Record<number, number>
  playAudioTrackOnEnterWeights?: Record<string, number>;
  locationBindings?: string[]; // Accessible to target X from current location Y.
  locationBindingRegularExpressionTriggers?: Record<string, string>
  characterBindings?: string[];
  globalWeight?: number;
  characterWeights?: Record<string, number>;
  ownerBindings?: string[]
  latitude?: number;
  longitude?: number;
  locationDistances?: Record<string, number>;
  messageFilterNonCoLocatedParticipants?: boolean;
  messageFilterRegularExpressionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  useBase64Encoding?: boolean;
}

export type localBackend =
  | 'Llama.cpp' | 'Transformers' | 'ExLlamaV3' | 'ExLlamaV3 HF'
  | 'ExLlamaV2' | 'TensorRT-LLM' | 'Ollama'
  | 'vLLM' | 'SGLang' | 'LM Studio' | 'LocalAI' | 'mistral.rs';

export type cloudBackend = 'DeepSeek' | 'Qwen' | 'Kimi' | 'GLM' | 'MiMo' | 'Minimax' | 'Google' | 'OpenAI' | 'Anthropic' | 'Mistral' | 'Grok' | 'Groq' | 'YandexGPT' | 'OpenRouter' | 'Inworld' | 'Cohere' | 'AI21' | 'Perplexity' | 'NovelAI' | 'Other'

export type backend = localBackend | cloudBackend
export interface LanguageModel extends ObjectData {
  backend: backend;
  contextLength: number;
  model?: string;
  mmproj?: string;
  lora?: string;
  apiKey?: string;
  parameters?: Record<string, unknown>;
  instructionTemplate?: string;
  chatTemplate?: string;
  cacheHitCostPerOneMillionOfTokens?: number;
  cacheMissCostPerOneMillionOfTokens?: number;
  outputGenerationCostPerOneMillionOfTokens?: number;
}

export interface RawLanguageModel extends RawData {
  backend: backend;
  contextLength: number;
  model?: string;
  mmproj?: string;
  lora?: string;
  apiKey?: string;
  parameters?: Record<string, unknown>;       // e.g., "<|im_start|>{role}\n{content}<|im_end|>\n"
  instructionTemplate?: string;
  chatTemplate?: string;
  cacheHitCostPerOneMillionOfTokens?: number;
  cacheMissCostPerOneMillionOfTokens?: number;
  outputGenerationCostPerOneMillionOfTokens?: number;
}

export interface Memory extends ObjectData {
  content: string;
  interactionData: InteractionData;
}

export interface RawMemory extends RawData {
  content: string;
  interactionDataId: string;
}

export type tool = "whisper" | "think" | "pick" | "clock" | "calendar" | "coin" | "dice" | "random" | "rng" | "move" | "timer" | "stopwatch" | "schedule" | "calculator" | "web" | "lookup" | "map" | "audio" | "note" | "inventory" | "trade" | "invite" | "kick" | "teleport" | "key" | "dialogue" | "knowledge" | "memory" | "clothing" | "summon" | "narrate" | "inspect" | "administrator" | "creator" | "destroyer"

export interface DialoguePrompt extends ObjectData {
  content: string;
  dialoguePromptBindings: string[]; // IDs of dialogue prompts this can chain to.
  dialoguePromptWeight: number // This dialogue prompt weight when being a part of the dialogue prompt or the start of it. Default is 1.
  dialoguePromptBreakProbability: number; // The higher the value, the higher the probability that the dialogue prompt will break before it can go to next node. Default is 0.
  dialoguePromptSkipProbability: number // The higher the value, the higher the likelihood of skipping choosing the dialogue from this node. Default is 0.
  regularExpressionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
}

export interface KnowledgePrompt extends ObjectData {
    content: string;
    knowledgePromptBindings: string[]; // IDs of other KnowledgePrompts this links to
    regularExpressionActivationTriggers?: RegularExpressionTrigger[];
    regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
    regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
    regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
}
export interface Clothing extends ObjectData {
    regularExpressionActivationTriggers?: RegularExpressionTrigger[];
    regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
    initialWearingProbability: number // Higher the number, the more likely it is being worn when this character becomes a participant of chat session. Default is 1.
    clothingBindings: string[] // IDs of clothing items this one hides when worn.
}

export interface TextCharacterInjection extends ObjectData {

  textCharacters: string[];
  textCharacterWeights: Record<number, number>; // Positional index -> weight value.
  textCharacterInjectionBindings: string[]; // Next IDs to go to once this text is generated.
  textCharacterInjectionWeight: number // This text character injection weight when being a part of next injection or the start of it. Default is 1.
  textCharacterBreakProbability: number; // The higher the value, the higher the probability that the character will break before it can go to next weights. Default is 0.
  textCharacterSkipProbability: number // The higher the value, the higher the likelihood of skipping choosing a text from this node. Default is 0.

}

export interface Character extends ObjectData {
  aliases?: string[],
  images?: Record<string, string>;
  useFrontCameraImage?: boolean; // Default is false.
  voice?: string;
  systemPrompt?: string;
  thinkPrompt?: string;
  appearancePrompt?: string;
  dialoguePrompts?: DialoguePrompt[];
  knowledgePrompts?: KnowledgePrompt[];
  starterPrompts?: Record<string, number>; // Text -> Weight value for that text during the sampling.
  memoryPrompts?: Record<string, string>; // Expression -> string. If the string for this expression is not found, then use neutral. If no neutral string, then use system default. Used for creation of memories.
  initiativeWeight: number;
  chatProbability: number;
  maximumChatStamina: number;
  nameSensitivity: number;
  chatImpatienceSensitivity: number;
  skipProbability: number;
  memoryRetentionWeight: number;
  contextSensitivity: number;
  maximumActionStamina: number;
  sampler?: Sampler | undefined;
  stopPatterns?: StopPattern[];
  doNotInjectCharacterImage?: boolean;
  numberOfMessagesToDisableThinkPrompt: number;
  numberOfMessagesToDisableMetaThinkInstructions: number;
  numberOfMessagesToDisableDialoguePrompt: number;
  numberOfMessagesToDisableStarterPrompt: number;
  tools: Record<tool, boolean>
  clothings: Clothing[];
  knownCharacterNames: Record<string, string[]> // Character Ids -> character names + aliases known by this character.
  textCharacterInjections: TextCharacterInjection[],
  memories: Record<string, Memory[]>;
}

export interface RawCharacter extends RawData {
  aliases?: string[],
  images?: Record<string, string>;
  useFrontCameraImage?: boolean; // Default is false.
  voice?: string;
  systemPrompt?: string;
  thinkPrompt?: string;
  appearancePrompt?: string;
  dialoguePrompts?: DialoguePrompt[];
  knowledgePrompts?: KnowledgePrompt[];
  starterPrompts?: Record<string, number>; // Text -> Weight value for that text during the sampling.
  memoryPrompts?: Record<string, string>; // Expression -> string. If the string for this expression is not found, then use neutral. If no neutral string, then use system default. Used for creation of memories.
  initiativeWeight: number;
  chatProbability: number;
  maximumChatStamina: number;
  nameSensitivity: number;
  chatImpatienceSensitivity: number;
  skipProbability: number;
  memoryRetentionWeight: number;
  contextSensitivity: number;
  maximumActionStamina: number;
  samplerId?: string | undefined;
  stopPatternIds?: string[];
  doNotInjectCharacterImage?: boolean;
  numberOfMessagesToDisableThinkPrompt: number;
  numberOfMessagesToDisableMetaThinkInstructions: number;
  numberOfMessagesToDisableDialoguePrompt: number;
  numberOfMessagesToDisableStarterPrompt: number;
  tools: Record<tool, boolean>
  clothings: Clothing[];
  knownCharacterNames: Record<string, string[]> // Character Ids -> character names + aliases known by this character.
  textCharacterInjections: TextCharacterInjection[],
  memories: Record<string, string[]>;
}

export type inventoryInfo = string | number

export type Inventory = Record<string, inventoryInfo>

export interface BaseMessage {
  id: string;
  character: Character;
  remainingChatStamina?: number;
  remainingActionStamina?: number;
  knownCharacterNames?: Record<string, Record<string, boolean>>; // Character Ids -> Character name + aliases -> The character name + aliases that is known by the message holder.
  characterExpression?: string;
  inventory?: Inventory,
  characterClothingWearingStatuses: Record<string, boolean>
  characterLockedLocations: Record<string, string[]> // Location Ids -> An array of character Ids.
  isPresent?: boolean;
  isConverged?: boolean; // Because when traversing the messages in reverse at convergence, it would take the wrong path as it does not see it made that jump.
  parentMessageId?: string | null;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;
}

export interface InteractionMessage extends BaseMessage {
  messageType: 'interaction';
}

export interface ChatMessage extends BaseMessage {
  messageType: 'chat';
  textContent: string;
  files?: string[];
  frontCameraImage?: string;
  doNotRespond: boolean;
  modelTextContentSummaries: Record<string, string>;
  modelInteractionTextContentSummaries: Record<string, string>;
  kvCacheTextContentPaths: Record<string, string>;
  kvCacheTextContentSummaryPaths: Record<string, string>;
  kvCacheInteractionTextContentSummaries: Record<string, string>;
}

export interface WhisperMessage extends BaseMessage {
  messageType: 'whisper';
  textContent: string;
  targetCharacterIds: string[];
  files?: string[];
  frontCameraImage?: string;
  modelTextContentSummaries: Record<string, string>;
  modelInteractionTextContentSummaries: Record<string, string>;
  kvCacheTextContentPaths: Record<string, string>;
  kvCacheTextContentSummaryPaths: Record<string, string>;
  kvCacheInteractionTextContentSummaries: Record<string, string>;
}

export type HistoryMessage = InteractionMessage | ChatMessage | WhisperMessage;

export interface RawBaseMessage {
  characterId: string;
  remainingChatStamina?: number;
  remainingActionStamina?: number;
  knownCharacterNames?: Record<string, Record<string, boolean>>; // Character Ids -> Character name + aliases -> The character name + aliases that is known by the message holder.
  characterExpression?: string;
  inventory?: Inventory,
  isPresent?: boolean;
  isConverged?: boolean; // Because when traversing the messages in reverse at convergence, it would take the wrong path as it does not see it made that jump.
  parentMessageId?: string | null;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;
}

export interface RawInteractionMessage extends RawBaseMessage {
  messageType: 'interaction';
}

export interface RawChatMessage extends RawBaseMessage {
  messageType: 'chat';
  textContent: string;
  files?: string[];
  frontCameraImage?: string;
  modelTextContentSummaries: Record<string, string>;
  modelInteractionTextContentSummaries: Record<string, string>;
  kvCacheTextContentPaths: Record<string, string>;
  kvCacheTextContentSummaryPaths: Record<string, string>;
  kvCacheInteractionTextContentSummaries: Record<string, string>;
}

export interface RawWhisperMessage extends RawBaseMessage {
  messageType: 'whisper';
  textContent: string;
  targetCharacterIds: string[];
  files?: string[];
  frontCameraImage?: string;
  modelTextContentSummaries: Record<string, string>;
  modelInteractionTextContentSummaries: Record<string, string>;
  kvCacheTextContentPaths: Record<string, string>;
  kvCacheTextContentSummaryPaths: Record<string, string>;
  kvCacheInteractionTextContentSummaries: Record<string, string>;
}

export type RawHistoryMessage = RawInteractionMessage | RawChatMessage | RawWhisperMessage;
export interface Account extends ObjectData {

  username: string
  password: string
  url?: string
  sharedCharacterIds: string[];
  sharedLanguageModelIds: string[];

}

export interface RawAccount extends RawData {

  username: string
  password: string
  url?: string
  sharedCharacterIds: string[];
  sharedLanguageModelIds: string[];

}

export interface MultiplayerDataAccountConfiguration {

  isWhitelisted: boolean; // If not whitelisted, it must go through the pendingAccountIds for joining again.
  isBlacklisted: boolean;
  isAdministrator: boolean;

  canUseJoinerCharacterIds: boolean;
  joinerCharacterIdsRequiresHosterApproval: boolean;

  sharedHosterCharacterIds: string[];
  hosterCharacterIdsRequiresHosterApproval: boolean;

  whitelistedCharacterIds: string[];
  blacklistedCharacterIds: string[];
  pendingCharacterIds: string[];

  protagonistCharacterId?: string; // Current protagonist id that is chosen by the joiner.

}

export interface MultiplayerData extends ObjectData {

  password: string // Password - invite only. No password - accessible for all.
  canUseJoinerCharacterIds: boolean;
  joinerCharacterIdsRequiresHosterApproval: boolean;
  sharedHosterCharacterIds: string[];
  hosterCharacterIdsRequiresHosterApproval: boolean;
  useJoinerLanguageModel: tristateInteger; // -1 - Disabled, use hoster's language model only. 0 - Use joiner's when given. 1 - Mandatory for the joiner to give access for the language model or they cannot join.
  interactionDataIds: string[]
  multiplayerDataAccountConfigurations: Record<string, MultiplayerDataAccountConfiguration> // Account Id -> MultiplayerDataAccountConfiguration
  pendingAccountIds: string[] // Received the join request, and is waiting for the hoster's decision.

}

export interface RawMultiplayerData extends RawData {

  password: string // Password - invite only. No password - accessible for all.
  canUseJoinerCharacterIds: boolean;
  joinerCharacterIdsRequiresHosterApproval: boolean;
  sharedHosterCharacterIds: string[];
  hosterCharacterIdsRequiresHosterApproval: boolean;
  useJoinerLanguageModel: tristateInteger; // -1 - Disabled, use hoster's language model only. 0 - Use joiner's when given. 1 - Mandatory for the joiner to give access for the language model or they cannot join.
  interactionDataIds: string[]
  multiplayerDataAccountConfigurations: Record<string, MultiplayerDataAccountConfiguration> // Account Id -> MultiplayerDataAccountConfiguration
  pendingAccountIds: string[] // Received the join request, and is waiting for the hoster's decision.

}

export interface InteractionData extends ObjectData {
  protagonists: Character[];
  participants: Character[];
  contexts: Context[];
  locations: Location[];
  audioTracks: AudioTrack[];
  interactionHistories: Record<string, HistoryMessage[]>; // location Id -> InteractionHistory at that location.
  numberOfMessages?: number;
  parentInteractionDataId?: string | null;
  parentMessageId?: string | null;
  Profile?: Profile;
}

export interface RawInteractionData extends RawData {
  protagonistIds: string[];
  participantIds: string[];
  contextIds: string[];
  locationIds: string[];
  audioTrackIds: string[];
  interactionHistories: Record<string, string[]>; // location Id -> InteractionHistory at that location.
  parentInteractionDataId?: string | null;
  parentMessageId?: string | null;
  ProfileId?: string;
}

export type ExtensionType = 'Image Generation API' | 'Accessibility' | 'Extra';

export interface Extension extends ObjectData {
  extensionType: ExtensionType;
  priority: number,
}

export interface BudgetStrategy extends ObjectData {
  modelIds: string[];
  modelCostTiers: Record<string, number>
  modelLatencyMsPerTokenTiers: Record<string, number>
  modelTimeToFirstTokenTiers: Record<string, number>
  modelQualityTiers: Record<string, number>
  modelActivationContextSize: Record<string, number> // Model Id -> The number of tokens for enable the model.
  modelDeactivationContextSize: Record<string, number> // Model Id -> The number of tokens for disabling the model. 
  maximumBudget: number;
}

export interface RawBudgetStrategy extends RawData {
  modelIds: string[];
  modelCostTiers: Record<string, number>
  modelLatencyMsPerTokenTiers: Record<string, number>
  modelTimeToFirstTokenTiers: Record<string, number>
  modelQualityTiers: Record<string, number>
  modelActivationContextSize: Record<string, number> // Model Id -> The number of tokens for enable the model.
  modelDeactivationContextSize: Record<string, number> // Model Id -> The number of tokens for disabling the model. 
  maximumBudget: number;
}

export interface BudgetData extends ObjectData {
  budgetSpent: number
  resetDuration: number
  averageLatencyMsPerTokenExponentialMovingAverageSmoothing: number;
  averageTimeToFirstTokenExponentialMovingAverageSmoothing: number;
  modelLastUsedTimestamps: Record<string, number>
  modelLastQuotaHitTimeStamps: Record<string, number>
  modelLastErrorHitTimeStamps: Record<string, number>
  modelUsedCount: Record<string, number>
  modelRegenerationCount: Record<string, number>;
  modelCensorshipHitCount: Record<string, number>;
  modelBrokenCount: Record<string, number>;
  modelQuotaHitCount: Record<string, number>
  modelErrorHitCount: Record<string, number>
  lastResetTimestamp: number
  budgetStrategy: BudgetStrategy
  modelBudgetSpent: Record<string, number>
  modelAverageLatencyMsPerToken: Record<string, number>;
  modelAverageTimeToFirstToken: Record<string, number>
  modelTotalSessionDuration: Record<string, number>
}

export interface RawBudgetData extends RawData {
  budgetSpent: number
  resetDuration: number
  averageLatencyMsPerTokenExponentialMovingAverageSmoothing: number;
  averageTimeToFirstTokenExponentialMovingAverageSmoothing: number;
  modelLastUsedTimestamps: Record<string, number>
  modelLastQuotaHitTimeStamps: Record<string, number>
  modelLastErrorHitTimeStamps: Record<string, number>
  modelUsedCount: Record<string, number>
  modelRegenerationCount: Record<string, number>;
  modelCensorshipHitCount: Record<string, number>;
  modelBrokenCount: Record<string, number>;
  modelQuotaHitCount: Record<string, number>
  modelErrorHitCount: Record<string, number>
  lastResetTimestamp: number
  budgetStrategyId: string
  modelBudgetSpent: Record<string, number>
  modelAverageLatencyMsPerToken: Record<string, number>;
  modelAverageTimeToFirstToken: Record<string, number>
  modelTotalSessionDuration: Record<string, number>
}

export type SummarizationStrategyType =
  | 'Sliding Window Replace'
  | 'Periodic Compression'
  | 'Recursive Summary'
  | 'Observation Masking'
  | 'Entropy Pruning';

export interface SummarizationStep extends ObjectData {
  strategyType: SummarizationStrategyType;
  enabled: boolean;
  order: number;
  slidingWindowSize?: number;
  periodicCompressionInterval?: number;
  periodicCompressionChunkSize?: number;
  recursiveSummaryChunkSize?: number;
  recursiveSummaryMaximumDepth?: number;
  maskingRelevanceThreshold?: number;
  maskingKeywordWeight?: number;
  summaryTokenBudget?: number;
  summaryModelId?: string;
  triggerTokenThreshold?: number;
  entropyPruningChunkSize?: number;        // Messages per chunk (default: 3)
  entropyPruningThreshold?: number;        // Below this = fluff (default: 0.35)
  entropyPruningTokenBudget?: number;      // Max tokens to keep raw (default: 2000)
}

export interface RawSummarizationStep extends RawData {
  strategyType: SummarizationStrategyType;
  enabled: boolean;
  order: number;
  slidingWindowSize?: number;
  periodicCompressionInterval?: number;
  periodicCompressionChunkSize?: number;
  recursiveSummaryChunkSize?: number;
  recursiveSummaryMaximumDepth?: number;
  maskingRelevanceThreshold?: number;
  maskingKeywordWeight?: number;
  summaryTokenBudget?: number;
  summaryModelId?: string;
  triggerTokenThreshold?: number;
  entropyPruningChunkSize?: number;        // Messages per chunk (default: 3)
  entropyPruningThreshold?: number;        // Below this = fluff (default: 0.35)
  entropyPruningTokenBudget?: number;      // Max tokens to keep raw (default: 2000)
}

export type promptBlockType =
  | 'System Prompt'
  | 'Think Prompt'
  | 'Meta Think Instructions'
  | 'Appearance Prompt'
  | 'Dialogue Prompt'
  | 'Chat History'
  | 'Context'
  | 'Location'
  | 'Weather'
  | 'Inventory'
  | 'Date'
  | 'Time'
  | 'Time Elapsed'
  | 'Fatigue Information'
  | 'Starter Prompt'
  | 'Tool Instructions'
  | 'Anti-Repetition Nudge'
  | 'Text Injection'
  | 'Model Chat Template'
  | 'Model Instruction Template'
  | 'Model Chat-Instruction Template'

export interface PromptBlock extends ObjectData {
  textContent: string
  images: string[]
  regularExpressionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  characterBindings: string[]
  contextBindings: string[]
  locationBindings: string[]
}

export interface RawPromptBlock extends RawData {
  textContent: string
  images: string[]
  regularExpressionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
  messageFilterRegularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
  characterBindings: string[]
  contextBindings: string[]
  locationBindings: string[]
}

export type textType = "normal" | "quoted" | "bolded" | "italicized" | "parenthesized" | "bracketed" | "braced"

export type toolUsageDisplayMode = "none" | "icon" | "simple" | "detailed" | "full" | "raw" // Default is none.

export type cacheEfficiencyConfigurationType = 'Character Name' | 'System Prompt' | 'Think Prompt' // 0 -> No optimization, 1 -> Limited to co-located participants, 2 -> All participants
export interface Profile extends ObjectData {
  autonomousMode: boolean;
  autonomousInteractionIntervalMs: number;
  volume: number;
  forceNameReveal: boolean;
  enableAmbientNarration: boolean; // Default is false.
  toolUsageDisplayMode: toolUsageDisplayMode;
  enableCharacterExpression: boolean;
  randomizeTextCharacterInjection: boolean;
  randomizeTextCharacterInjectionOnRetry: boolean; // Only randomize if the initial randomization fails. Default is true. This setting get revealed when randomizeTextCharacterInjection is true.
  maximumNumberOfTextCharacterRandomizationPerModel: number; // Number of retries to get the text generated per model. Default is 1. This setting get revealed when randomizeTextCharacterInjection is true.
  forceNoCharacterImageInjection: boolean;
  forceNoContextImageInjection: boolean;
  forceNoLocationImageInjection: boolean;
  weatherApiKey?: string;
  useFrontCameraImage: tristateInteger; // -1 -> Disabled for all character, 0 -> Per-Character (Default), 1 -> Enabled for all character.
  numberOfMessagesToDisableThinkPrompt: number;
  numberOfMessagesToDisableMetaThinkInstructions: number;
  numberOfMessagesToDisableDialoguePrompt: number;
  numberOfMessagesToDisableStarterPrompt: number;
  forceEqualInitiative: boolean;
  chatProbability: number;
  maximumChatStamina: number;
  nameSensitivity: number;
  chatImpatienceSensitivity: number;
  skipProbability: number;
  memoryRetentionWeight: number;
  contextSensitivity: number;
  maximumActionStamina: number;
  cacheEfficiencyLevels: Record<cacheEfficiencyConfigurationType, number>;
  minimalVolatileCacheMode: boolean // A switch that forces the input strategy to be locked to specific configuration to maximize cache efficiency.
  doNotInjectDefaultStopTokens: boolean;
  narrateTexts: Record<textType, boolean>;
  stripThinkTokens: boolean;
  tools: Record<tool, tristateInteger>;
  inputStrategy: (promptBlockType | string)[];
  summarizationSteps: SummarizationStep[];
  summarizationInstruction?: string // If empty, then use in-built default.
  enableSpeculativeMarkov: boolean;
  characterSampler?: Sampler;
  webSummarizationSampler?: Sampler;
  interactionDataSummarizationSampler?: Sampler;
  aiRecommendationSampler?: Sampler;
  characterStopPattern?: StopPattern;
  webSummarizationStopPattern?: StopPattern;
  interactionDataSummarizationStopPattern?: StopPattern;
  aiRecommendationStopPattern?: StopPattern;
}

export interface RawProfile extends RawData {
  autonomousMode: boolean;
  autonomousInteractionIntervalMs: number;
  volume: number;
  forceNameReveal: boolean;
  enableAmbientNarration: boolean; // Default is false.
  toolUsageDisplayMode: toolUsageDisplayMode;
  enableCharacterExpression: boolean;
  randomizeTextCharacterInjection: boolean;
  randomizeTextCharacterInjectionOnRetry: boolean; // Only randomize if the initial randomization fails. Default is true. This setting get revealed when randomizeTextCharacterInjection is true.
  maximumNumberOfTextCharacterRandomizationPerModel: number; // Number of retries to get the text generated per model. Default is 1. This setting get revealed when randomizeTextCharacterInjection is true.
  forceNoCharacterImageInjection: boolean;
  forceNoContextImageInjection: boolean;
  forceNoLocationImageInjection: boolean;
  weatherApiKey?: string;
  useFrontCameraImage: tristateInteger; // -1 -> Disabled for all character, 0 -> Per-Character (Default), 1 -> Enabled for all character.
  numberOfMessagesToDisableThinkPrompt: number;
  numberOfMessagesToDisableMetaThinkInstructions: number;
  numberOfMessagesToDisableDialoguePrompt: number;
  numberOfMessagesToDisableStarterPrompt: number;
  forceEqualInitiative: boolean;
  chatProbability: number;
  maximumChatStamina: number;
  nameSensitivity: number;
  chatImpatienceSensitivity: number;
  skipProbability: number;
  memoryRetentionWeight: number;
  maximumActionStamina: number;
  contextSensitivity: number;
  cacheEfficiencyLevels: Record<cacheEfficiencyConfigurationType, number>;
  minimalVolatileCacheMode: boolean // A switch that forces the input strategy to be locked to specific configuration to maximize cache efficiency.
  doNotInjectDefaultStopTokens: boolean;
  narrateTexts: Record<textType, boolean>;
  stripThinkTokens: boolean;
  tools: Record<tool, tristateInteger>;
  inputStrategy: (promptBlockType | string)[];
  summarizationSteps: RawSummarizationStep[];
  summarizationInstruction?: string // If empty, then use in-built default.
  enableSpeculativeMarkov: boolean;
  characterSamplerId?: string;
  webSummarizationSamplerId?: string;
  interactionDataSummarizationSamplerId?: string;
  aiRecommendationSamplerId?: string;
  characterStopPatternId?: string;
  webSummarizationStopPatternId?: string;
  interactionDataSummarizationStopPatternId?: string;
  aiRecommendationStopPatternId?: string;
}

export interface InterjectableAction {
  label: string;
  count: number;
}

export interface World extends ObjectData {
    characterIds: string[];
    contextIds: string[];
    locationIds: string[];
    audioTrackIds: string[];
    promptBlockIds: string[]
    profileId?: string;
}

export interface ParsedCharacterCard {
  name: string;
  description: string;
  firstMes: string;
  personality?: string;
  scenario?: string;
  mesExample?: string;
  creatorNotes?: string;
  systemPrompt?: string;
  starterPrompt?: string;
  alternateGreetings?: string[];
  tags?: string[];
  creator?: string;
  characterVersion?: string;
}

export interface Webpage extends ObjectData {
  url: string;
  content: string;
}

export interface RawWebpage extends RawData {
  url: string;
  content: string;
}

export type audioCategory = 'ambient' | 'music' | 'sound effect'

export interface AudioTrack extends ObjectData {
    filename: string;
    loop: boolean;
    volume: number;
    audioCategory: audioCategory;
    playableByParticipants: boolean;
    startFadeDurationMs: number;
    endFadeDurationMs: number;
    regularExpressionActivationTriggers?: RegularExpressionTrigger[];
    regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
    regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
    regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
    locationBindings: string[];
    contextBindings: string[]
    characterBindings: string[];
    priority: number;
}

export interface RawAudioTrack extends RawData {
    filename: string;
    loop: boolean;
    volume: number;
    audioCategory: audioCategory;
    playableByParticipants: boolean;
    startFadeDurationMs: number;
    endFadeDurationMs: number;
    regularExpressionActivationTriggers?: RegularExpressionTrigger[];
    regularExpressionDeactivationTriggers?: RegularExpressionTrigger[];
    regularExpressionExclusionActivationTriggers?: RegularExpressionTrigger[];
    regularExpressionExclusionDeactivationTriggers?: RegularExpressionTrigger[];
    locationBindings: string[];
    contextBindings: string[];
    characterBindings: string[];
    priority: number; 
}

export interface SessionData {
    selectedCharacterId?: string | null;
    selectedModelId?: string | null;
    selectedProfileId?: string | null;
    selectedBudgetStrategyId?: string | null;
    activeChatId?: string | null;
    currentAccountId?: string | null;
    activeExtensionIds?: string[]
}

export interface MultiplayerJoinData {
    joinSessionId?: string | null;
    joinPassword?: string | null;
    joinProtagonist?: Character | null;
    joinRequestedCharacterId?: string | null;
    joinRequestedCharacterData?: Character | null;
}

export interface ActionFormatData {
    actionWrap?: '*' | '()' | 'none';
    actionCase?: 'first' | 'pascal' | 'lower';
    actionPunctuation?: '.' | '-' | 'none';
    isAutoFormat?: boolean;
    matrix?: Record<string, Record<string, number>>;
}

export type Entity = Character | Context | Location | AudioTrack | World | PromptBlock | LanguageModel | Sampler | StopPattern | Profile | BudgetStrategy | Account | MultiplayerData

export type entityType = 
    | 'character' | 'context' | 'location' | 'audioTrack' 
    | 'world' | 'model' | 'sampler' | 'promptBlock' 
    | 'stopPattern' | 'budgetStrategy' | 'profile' 
    | 'account' | 'multiplayerData';