interface ObjectData {

  id: string;
  name: string;
  description?: string;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;

}

interface RawData {

  name: string;
  description?: string;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;

}

export interface StopPattern extends ObjectData {

  pattern: string;
  regularExpressionTrigger?: string;
  regularExpressionContext?: 'global' | 'local' | 'previous';
  regularExpressionTarget?: 'everyone' | 'listener' | 'self';

}

export interface RawStopPattern extends RawData {

  pattern: string;
  regularExpressionTrigger?: string;
  regularExpressionContext?: 'global' | 'local' | 'previous';
  regularExpressionTarget?: 'everyone' | 'listener' | 'self';

}

export interface Sampler extends ObjectData {

  parameters?: Record<string, unknown>;
  stopPatterns: StopPattern[];
  maximumNumberOfTokens?: number;
  
}

export interface RawSampler extends RawData  {

  parameters?: Record<string, unknown>;
  stopPatternIds: string[];
  maximumNumberOfTokens?: number;

}

export type searchEngine = "Google" | "Bing" | "DuckDuckGo" | "Yandex" | "Baidu"

export interface Context extends ObjectData {
    text?: string;
    images?: string[];
    searchTerms?: string[]
    searchEngine?: searchEngine
    urls?: string[];              // URL to fetch content from
    includeLinkImages?: boolean// Can fetched content trigger further context entries?
    maximumLinkDepth?: number;           // Max depth for recursive link following (overrides global)
    linkFetchMode?: 'full' | 'summary' | 'extract'; // How to process fetched content
    limitLinksToSubdirectory: boolean;
    fetchCacheTimeToLiveMs?: number;        // Cache TimeToLive in ms (0 = always refetch, default = 300000 / 5min)
    regularExpressionTrigger?: string;
    regularExpressionContext?: 'global' | 'local' | 'previous';
    regularExpressionTarget?: 'everyone' | 'listener' | 'self';
    tokenBudget?: number;
    maximumRecursionDepth?: number;
    insertionDepth?: number;
    characterBindings?: string[];
    useBase64Encoding: boolean;
    isAutoGenerated?: boolean;
}

export interface RawContext extends RawData {
    text?: string;
    images?: string[];
    searchTerms?: string[]
    searchEngine?: searchEngine
    urls?: string[];
    includeLinkImages?: boolean
    maximumLinkDepth?: number;
    linkFetchMode?: 'full' | 'summary' | 'extract';
    limitLinksToSubdirectory: boolean;
    fetchCacheTimeToLiveMs?: number;
    regularExpressionTrigger?: string;
    regularExpressionContext?: 'global' | 'local' | 'previous';
    regularExpressionTarget?: 'everyone' | 'listener' | 'self';
    tokenBudget?: number;
    maximumRecursionDepth?: number;
    insertionDepth?: number;
    characterBindings?: string[];
    useBase64Encoding: boolean;
    isAutoGenerated?: boolean;
}

export type backend = 'Llama.cpp' | 'Transformers' | 'ExLlamaV3' | 'ExLlamaV3 HF' | 'TensorRT-LLM' | 'Ollama' | 'DeepSeek' | 'Qwen' | `Kimi` | 'GLM' | 'MiMo' |'OpenAI' | 'Mistral' | 'Groq'| 'YandexGPT' |'OpenRouter' | 'Inworld' | 'Other'

export interface LanguageModel extends ObjectData {

  backend?: backend;
  contextLength: number;
  model?: string;
  mmproj?: string;
  lora?: string;
  apiKey?: string;
  parameters?: Record<string, unknown>;
  cacheHitCostPerOneMillionOfTokens?: number,
  cacheMissCostPerOneMillionOfTokens?: number,
  outputGenerationCostPerOneMillionOfTokens?: number,

}

export interface RawLanguageModel extends RawData {

  backend?: backend;
  contextLength: number;
  model?: string;
  mmproj?: string;
  lora?: string;
  apiKey?: string;
  parameters?: Record<string, unknown>;
  cacheHitCostPerOneMillionOfTokens?: number,
  cacheMissCostPerOneMillionOfTokens?: number,
  outputGenerationCostPerOneMillionOfTokens?: number,

}
export interface Character extends ObjectData  {
  
  image?: string; // Path to the character's image.
  voice?: string; // Path to the character's voice.
  systemPrompt?: string;
  thinkPrompt?: string;
  appearancePrompt?: string;
  dialoguePrompt?: string;
  initiativeWeight: number;
  chatProbability: number;
  maximumChatStamina: number;
  sampler?: Sampler | undefined;
  stopPatterns?: [StopPattern]
  doNotInjectCharacterImage?: boolean;

}

export interface RawCharacter extends RawData {

  image?: string; // Path to the character's image.
  voice?: string; // Path to the character's voice.
  systemPrompt?: string;
  thinkPrompt?: string;
  appearancePrompt?: string;
  dialoguePrompt?: string;
  initiativeWeight: number;
  chatProbability: number;
  maximumChatStamina: number;
  samplerId?: string | undefined; // Store only the sampler ID here
  stopPatternIds?: [number]
  doNotInjectCharacterImage?: boolean;

}

export interface ChatMessage {
  
  id: string;
  character: Character;
  textContent: string;
  remainingChatStamina: number | undefined;
  isNameRevealed?: boolean;
  isPartial?: boolean; // ✅ True if generation was interrupted mid-stream
  textContentSummary?: string;
  kvCachePath?: string;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;
  parentChatMessageId?: string | null;

}

export interface RawChatMessage {

  characterId: string;
  textContent: string;
  remainingChatStamina: number | undefined;
  isNameRevealed?: boolean;
  isPartial?: boolean; // ✅ True if generation was interrupted mid-stream
  textContentSummary?: string;
  kvCachePath?: string;
  firstCreatedTimestamp: number;
  lastUpdatedTimestamp: number;
  parentChatMessageId?: string | null;

}

export interface ChatData extends ObjectData {

  protagonist: Character;
  participants: Character[];
  contexts?: Context[]; // Changed from instructions
  chatMessageHistory: ChatMessage[];
  messageCount?: number; // ✅ Total message count from metadata, available without loading messages
  parentChatDataId?: string | null;
  parentChatMessageId?: string | null;
  Profile?: Profile;

}

export interface RawChatData extends RawData {

  protagonistId: string;
  participantIds: string[];
  contextIds: string[]; // Changed from instructionIds
  chatMessageIdHistory: string[];
  parentChatDataId?: string | null;
  parentChatMessageId?: string | null;
  ProfileId?: string;
  

}

export type ExtensionType = 'Image Generation API' | 'Accessibility' | 'Extra';

export interface Extension extends ObjectData{

  extensionType: ExtensionType;

}

export interface BudgetStrategy extends ObjectData {

  onlineModel: LanguageModel;
  localModel: LanguageModel;
  switchProbabilty: number; //When the random value is less than the probability, the online model will be used.
  switchOnContextSize: number; //When the context size exceeds this limit, the online model will be used.
  switchOnComplexityScore: number, // When complexity score exceeds this limit, the online model will be used.
  fallbackOnLocalFailure: boolean; // If the local model fails to stop, the online model will be used.
  fallbackOnQualityThreshold: number;  // If the quality score below this, the online model will be used.
  fallbackOnTimeoutInSeconds: number; // If local takes too long, the online model will be used.
  maximumBudget: number; //When the cost exceeds the budget, then the local model will be used throughout the rest of the conversations.

}

export interface RawBudgetStrategy extends RawData {

  onlineModelId: string;
  localModelId: string;
  switchProbabilty: number; //When the random value is less than the probability, the online model will be used.
  switchOnContextSize: number; //When the context size exceeds this limit, the online model will be used.
  switchOnComplexityScore: number, // When complexity score exceeds this limit, the online model will be used.
  fallbackOnLocalFailure: boolean; // If the local model fails to stop, the online model will be used.
  fallbackOnQualityThreshold: number;  // If the quality score below this, the online model will be used.
  fallbackOnTimeoutInSeconds: number; // If local takes too long, the online model will be used.
  maximumBudget: number; //When the cost exceeds the budget, then the local model will be used throughout the rest of the conversations.

}

// Add to src/types.ts

// ✅ Summarization strategy types
export type SummarizationStrategyType = 
    | 'Sliding Window Replace'    // Option 1: Replace old messages with per-message summaries
    | 'Periodic Compression'      // Option 3: Compress every M messages into a paragraph
    | 'Recursive Summary'         // Option 2: Hierarchical chunk → meta → global summaries
    | 'Observation Masking'       // Option 4: Hide irrelevant old messages by relevance score

export interface SummarizationStep extends ObjectData {                    // Display name (e.g., "Sliding Window", "Periodic Compression")
    strategyType: SummarizationStrategyType;
    enabled: boolean;                    // Can be disabled independently
    order: number;                       // Execution order (lower = runs first)
    
    // --- Sliding Window Replace settings ---
    slidingWindowSize?: number;          // Keep last N messages verbatim (default: 10)
    
    // --- Periodic Compression settings ---
    compressionInterval?: number;        // Compress every M messages (default: 20)
    compressionChunkSize?: number;       // How many messages to compress at once (default: 10)
    
    // --- Recursive Summary settings ---
    recursiveChunkSize?: number;         // Messages per chunk at layer 0 (default: 10)
    recursiveMaxDepth?: number;          // Max recursion depth (default: 3)
    
    // --- Observation Masking settings ---
    maskingRelevanceThreshold?: number;  // Min relevance score to include (0.0-1.0, default: 0.3)
    maskingKeywordWeight?: number;       // Weight for keyword matching vs recency (0.0-1.0, default: 0.7)
    
    // --- Shared settings ---
    summaryTokenBudget?: number;         // Max tokens for generated summaries (default: 512)
    summaryModelId?: string;             // Which model to use for summarization (empty = use current model)
    triggerTokenThreshold?: number;      // Trigger when total tokens exceed this (0 = auto based on context length)
}

export interface RawSummarizationStep extends RawData{
    strategyType: SummarizationStrategyType;
    enabled: boolean;
    order: number;
    slidingWindowSize?: number;
    compressionInterval?: number;
    compressionChunkSize?: number;
    recursiveChunkSize?: number;
    recursiveMaxDepth?: number;
    maskingRelevanceThreshold?: number;
    maskingKeywordWeight?: number;
    summaryTokenBudget?: number;
    summaryModelId?: string;
    triggerTokenThreshold?: number;
}

export type PromptBlockType = 
  'System Prompt'        // Character system prompts
  | 'Think Prompt'
  | 'Meta Think Instruction'             // Active context entries (regex-matched)     // Think/meta-instruction prompts  
  | 'Appearance Prompt'
  | 'Chat History'         // Conversation history messages
  | 'Context'
  | 'Fatigue Information' 
  | 'Date And Time'
  | 'Dialogue Prompt'
  | 'Text Injection'

export interface Profile extends ObjectData {

  forceNameReveal: boolean;
  forceNoCharacterImageInjection: boolean;
  forceNoContextImageInjection: boolean;
  useCurrentDateAndTime: boolean;
  forceEqualInitiative: boolean;
  chatProbability: number; // 0 means it is disabled and uses character default.
  maximumChatStamina: number; // 0 means it is disabled and uses character default..
  cacheInvalidationReductionLevel: number // 0 for no cache invalidation reduction, 1 forces name injection, 2 forces prompt injection.
  narrateNormalText: boolean;
  narrateQuotedText: boolean;
  narrateBoldedText: boolean;
  narrateItalicizedText:boolean;
  stripThinkTokens: boolean;
  inputStrategy: PromptBlockType[] // Controls the order for which prompt is added first.
  summarizationSteps: SummarizationStep[];

}

export interface RawProfile extends RawData{

  forceNameReveal: boolean;
  forceNoCharacterImageInjection: boolean;
  forceNoContextImageInjection: boolean;
  useCurrentDateAndTime: boolean;
  forceEqualInitiative: boolean;
  chatProbability: number; // -1 means it is disabled and uses character default.
  maximumChatStamina: number; // -1 means it is disabled and uses character default..
  cacheInvalidationReductionLevel: number // 0 for no cache invalidation reduction, 1 forces name injection, 2 forces prompt injection.
  narrateNormalText: boolean;
  narrateQuotedText: boolean;
  narrateBoldedText: boolean;
  narrateItalicizedText:boolean;
  stripThinkTokens: boolean;
  inputStrategy: PromptBlockType[] // Controls the order for which prompt is added first.
  summarizationSteps: RawSummarizationStep[];

}

export interface InterjectableAction {
  label: string;
  count: number;
}
export interface ParsedCharacterCard {
    name: string;
    description: string;
    firstMes: string;
    personality?: string;
    scenario?: string;
    mesExample?: string;
    creatorNotes?: string;
    systemPrompt?: string;
    postHistoryInstructions?: string;
    alternateGreetings?: string[];
    tags?: string[];
    creator?: string;
    characterVersion?: string;
}

export interface Webpage extends ObjectData {

  url: string
  content: string

}

export interface RawWebpage extends RawData {

  url: string
  content: string

}